### ISSUE TITLE
REQUEST: ARM Docker Image

### ISSUE THREAD

**Issue by 53milesperburrito** [bachya/ecowitt2mqtt#10]
Greetings,

Thanks for making this project!

Would you mind making an ARM docker image? It would be very much appreciated for those of us deploying on an RPI. 

Thanks for considering!

**Comment by bachya** [comment]
@53milesperburrito #11 adds this. The images are in the process of their first publish, so if you don't see them right away, please be patient.

**Comment by bachya** [comment]
Follow up: `latest`, `dev`, and the latest version `0.1.1` now all have multi-arch builds. 👍

**Comment by 53milesperburrito** [comment]
You're a legend - thank you!
