### ISSUE TITLE
Add configuration options for MQTT message and session expiry

### ISSUE THREAD

**Issue by jwillmer** [bachya/ecowitt2mqtt#1024]
I would like to set the expiry interval for the MQTT messages. This allows me to display the values immediately on every new MQTT client. I dont like to use retain flag since this will keep the settings forever and can be confusing.

THe option that makes it possible is described at: https://www.hivemq.com/blog/mqtt5-essentials-part4-session-and-message-expiry/

**Comment by bachya** [comment]
I haven't found an explicit way to enable this via `aiomqtt` (the library we use for MQTT communications), but I'm still investigating.

**Comment by bachya** [comment]
Okay, I think I've found a way to add both parameters. Please test https://github.com/bachya/ecowitt2mqtt/pull/1037 and let me know!

**Comment by bachya** [comment]
Still active.
