### ISSUE TITLE
WARNING:mqtt:There are XX pending publish calls

### ISSUE THREAD

**Issue by edouardkleinhans** [bachya/ecowitt2mqtt#103]
**ecowitt2mqtt version**
2021.10.0-1

## System Health

version | core-2021.12.8
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.88
arch | x86_64
timezone | Europe/Paris

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
Github API Calls Remaining | 4795
Installed Version | 1.18.0
Stage | running
Available Repositories | 942
Installed Repositories | 32

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.1
-- | --
update_channel | stable
supervisor_version | supervisor-2021.12.2
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 20.9 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | AppDaemon 4 (0.7.2), Grafana (7.4.0), InfluxDB (4.3.0), Mosquitto broker (6.0.1), Rclone Backup (1.1.1), Studio Code Server (3.7.0), SSH & Web Terminal (10.0.0), ESPHome (2021.12.3), Frigate NVR (2.3), Samba share (9.5.1), File editor (5.3.3), Zigbee2mqtt (1.22.2-1), Terminal & SSH (9.2.2), MariaDB (2.4.0), Ecowitt (2021.10.0-1)

</details>

<details><summary>Lovelace</summary>

dashboards | 3
-- | --
resources | 18
views | 24
mode | storage

</details>

**Describe the bug**
<details><summary>Ecowitt addon logs</summary>
[11:56:16] INFO: Starting Ecowitt2MQTT
WARNING:mqtt:There are 11 pending publish calls.
WARNING:mqtt:There are 12 pending publish calls.
WARNING:mqtt:There are 13 pending publish calls.
WARNING:mqtt:There are 14 pending publish calls.
WARNING:mqtt:There are 15 pending publish calls.
WARNING:mqtt:There are 16 pending publish calls.
WARNING:mqtt:There are 17 pending publish calls.
WARNING:mqtt:There are 18 pending publish calls.
WARNING:mqtt:There are 19 pending publish calls.
WARNING:mqtt:There are 20 pending publish calls.
WARNING:mqtt:There are 21 pending publish calls.
WARNING:mqtt:There are 22 pending publish calls.
WARNING:mqtt:There are 23 pending publish calls.
WARNING:mqtt:There are 24 pending publish calls.
WARNING:mqtt:There are 25 pending publish calls.
WARNING:mqtt:There are 26 pending publish calls.
WARNING:mqtt:There are 27 pending publish calls.
WARNING:mqtt:There are 28 pending publish calls.
WARNING:mqtt:There are 29 pending publish calls.
WARNING:mqtt:There are 30 pending publish calls.
WARNING:mqtt:There are 31 pending publish calls.
WARNING:mqtt:There are 32 pending publish calls.
WARNING:mqtt:There are 33 pending publish calls.
WARNING:mqtt:There are 34 pending publish calls.
WARNING:mqtt:There are 35 pending publish calls.
WARNING:mqtt:There are 36 pending publish calls.
WARNING:mqtt:There are 37 pending publish calls.
WARNING:mqtt:There are 38 pending publish calls.
WARNING:mqtt:There are 39 pending publish calls.
WARNING:mqtt:There are 40 pending publish calls.
WARNING:mqtt:There are 41 pending publish calls.
WARNING:mqtt:There are 42 pending publish calls.
WARNING:mqtt:There are 43 pending publish calls.
WARNING:mqtt:There are 44 pending publish calls.
WARNING:mqtt:There are 45 pending publish calls.
WARNING:mqtt:There are 46 pending publish calls.
WARNING:mqtt:There are 47 pending publish calls.
WARNING:mqtt:There are 48 pending publish calls.
WARNING:mqtt:There are 49 pending publish calls.
WARNING:mqtt:There are 50 pending publish calls.
WARNING:mqtt:There are 51 pending publish calls.
WARNING:mqtt:There are 52 pending publish calls.
WARNING:mqtt:There are 53 pending publish calls.
WARNING:mqtt:There are 54 pending publish calls.
WARNING:mqtt:There are 55 pending publish calls.
WARNING:mqtt:There are 56 pending publish calls.
WARNING:mqtt:There are 57 pending publish calls.
WARNING:mqtt:There are 58 pending publish calls.
WARNING:mqtt:There are 59 pending publish calls.
WARNING:mqtt:There are 60 pending publish calls.
WARNING:mqtt:There are 61 pending publish calls.
WARNING:mqtt:There are 62 pending publish calls.
WARNING:mqtt:There are 63 pending publish calls.
WARNING:mqtt:There are 64 pending publish calls.
WARNING:mqtt:There are 65 pending publish calls.
WARNING:mqtt:There are 66 pending publish calls.
WARNING:mqtt:There are 67 pending publish calls.
WARNING:mqtt:There are 68 pending publish calls.
WARNING:mqtt:There are 69 pending publish calls.
WARNING:mqtt:There are 70 pending publish calls.
WARNING:mqtt:There are 71 pending publish calls.
WARNING:mqtt:There are 72 pending publish calls.
WARNING:mqtt:There are 73 pending publish calls.
WARNING:mqtt:There are 74 pending publish calls.
WARNING:mqtt:There are 75 pending publish calls.
WARNING:mqtt:There are 76 pending publish calls.
WARNING:mqtt:There are 77 pending publish calls.
WARNING:mqtt:There are 78 pending publish calls.
WARNING:mqtt:There are 79 pending publish calls.
WARNING:mqtt:There are 80 pending publish calls.
WARNING:mqtt:There are 81 pending publish calls.
WARNING:mqtt:There are 82 pending publish calls.
WARNING:mqtt:There are 83 pending publish calls.
WARNING:mqtt:There are 84 pending publish calls.
INFO:ecowitt2mqtt:Published to HASS discovery: {'tempin': 20.7, 'humidityin': 48, 'baromrel': 1098.308, 'baromabs': 1011.515, 'temp': 6.7, 'humidity': 76, 'winddir': 273, 'windspeed': 3.2, 'windgust': 7.2, 'maxdailygust': 5.82, 'solarradiation': 245.9, 'uv': 2, 'rainrate': 0.0, 'eventrain': 0.0, 'hourlyrain': 0.0, 'dailyrain': 0.2, 'weeklyrain': 31.2, 'monthlyrain': 31.5, 'yearlyrain': 31.5, 'totalrain': 31.5, 'wh65batt': 'off', 'wh25batt': 'off', 'dewpoint': 2.8, 'feelslike': 6.7, 'heatindex': 5.4, 'solarradiation_lux': 31126.6, 'solarradiation_perceived': 90.0, 'windchill': None}
INFO:ecowitt2mqtt:Published to HASS discovery: {'tempin': 20.0, 'humidityin': 48, 'baromrel': 1098.105, 'baromabs': 1011.312, 'temp': 6.8, 'humidity': 76, 'winddir': 169, 'windspeed': 1.1, 'windgust': 3.6, 'maxdailygust': 5.82, 'solarradiation': 252.38, 'uv': 2, 'rainrate': 0.0, 'eventrain': 0.0, 'hourlyrain': 0.0, 'dailyrain': 0.2, 'weeklyrain': 31.2, 'monthlyrain': 31.5, 'yearlyrain': 31.5, 'totalrain': 31.5, 'wh65batt': 'off', 'wh25batt': 'off', 'dewpoint': 2.8, 'feelslike': 6.8, 'heatindex': 5.5, 'solarradiation_lux': 31946.8, 'solarradiation_perceived': 90.0, 'windchill': None}
WARNING:mqtt:There are 11 pending publish calls.
WARNING:mqtt:There are 12 pending publish calls.
WARNING:mqtt:There are 13 pending publish calls.
WARNING:mqtt:There are 14 pending publish calls.
WARNING:mqtt:There are 15 pending publish calls.
WARNING:mqtt:There are 16 pending publish calls.
WARNING:mqtt:There are 17 pending publish calls.
WARNING:mqtt:There are 18 pending publish calls.
WARNING:mqtt:There are 19 pending publish calls.
WARNING:mqtt:There are 20 pending publish calls.
WARNING:mqtt:There are 21 pending publish calls.
WARNING:mqtt:There are 22 pending publish calls.
WARNING:mqtt:There are 23 pending publish calls.
WARNING:mqtt:There are 24 pending publish calls.
WARNING:mqtt:There are 25 pending publish calls.
WARNING:mqtt:There are 26 pending publish calls.
WARNING:mqtt:There are 27 pending publish calls.
WARNING:mqtt:There are 28 pending publish calls.
WARNING:mqtt:There are 29 pending publish calls.
WARNING:mqtt:There are 30 pending publish calls.
WARNING:mqtt:There are 31 pending publish calls.
WARNING:mqtt:There are 32 pending publish calls.
WARNING:mqtt:There are 33 pending publish calls.
WARNING:mqtt:There are 34 pending publish calls.
WARNING:mqtt:There are 35 pending publish calls.
WARNING:mqtt:There are 36 pending publish calls.
WARNING:mqtt:There are 37 pending publish calls.
WARNING:mqtt:There are 38 pending publish calls.
WARNING:mqtt:There are 39 pending publish calls.
WARNING:mqtt:There are 40 pending publish calls.
WARNING:mqtt:There are 41 pending publish calls.
WARNING:mqtt:There are 42 pending publish calls.
WARNING:mqtt:There are 43 pending publish calls.
WARNING:mqtt:There are 44 pending publish calls.
WARNING:mqtt:There are 45 pending publish calls.
WARNING:mqtt:There are 46 pending publish calls.
WARNING:mqtt:There are 47 pending publish calls.
WARNING:mqtt:There are 48 pending publish calls.
WARNING:mqtt:There are 49 pending publish calls.
WARNING:mqtt:There are 50 pending publish calls.
WARNING:mqtt:There are 51 pending publish calls.
WARNING:mqtt:There are 52 pending publish calls.
WARNING:mqtt:There are 53 pending publish calls.
WARNING:mqtt:There are 54 pending publish calls.
WARNING:mqtt:There are 55 pending publish calls.
WARNING:mqtt:There are 56 pending publish calls.
WARNING:mqtt:There are 57 pending publish calls.
WARNING:mqtt:There are 58 pending publish calls.
WARNING:mqtt:There are 59 pending publish calls.
WARNING:mqtt:There are 60 pending publish calls.
WARNING:mqtt:There are 61 pending publish calls.
WARNING:mqtt:There are 62 pending publish calls.
WARNING:mqtt:There are 63 pending publish calls.
WARNING:mqtt:There are 64 pending publish calls.
WARNING:mqtt:There are 65 pending publish calls.
WARNING:mqtt:There are 66 pending publish calls.
WARNING:mqtt:There are 67 pending publish calls.
WARNING:mqtt:There are 68 pending publish calls.
WARNING:mqtt:There are 69 pending publish calls.
WARNING:mqtt:There are 70 pending publish calls.
WARNING:mqtt:There are 71 pending publish calls.
WARNING:mqtt:There are 72 pending publish calls.
WARNING:mqtt:There are 73 pending publish calls.
WARNING:mqtt:There are 74 pending publish calls.
WARNING:mqtt:There are 75 pending publish calls.
WARNING:mqtt:There are 76 pending publish calls.
WARNING:mqtt:There are 77 pending publish calls.
WARNING:mqtt:There are 78 pending publish calls.
WARNING:mqtt:There are 79 pending publish calls.
WARNING:mqtt:There are 80 pending publish calls.
WARNING:mqtt:There are 81 pending publish calls.
WARNING:mqtt:There are 82 pending publish calls.
WARNING:mqtt:There are 83 pending publish calls.
WARNING:mqtt:There are 84 pending publish calls.
INFO:ecowitt2mqtt:Published to HASS discovery: {'tempin': 19.8, 'humidityin': 48, 'baromrel': 1098.409, 'baromabs': 1011.616, 'temp': 6.8, 'humidity': 77, 'winddir': 99, 'windspeed': 3.2, 'windgust': 5.4, 'maxdailygust': 5.82, 'solarradiation': 238.92, 'uv': 2, 'rainrate': 0.0, 'eventrain': 0.0, 'hourlyrain': 0.0, 'dailyrain': 0.2, 'weeklyrain': 31.2, 'monthlyrain': 31.5, 'yearlyrain': 31.5, 'totalrain': 31.5, 'wh65batt': 'off', 'wh25batt': 'off', 'dewpoint': 3.0, 'feelslike': 6.8, 'heatindex': 5.5, 'solarradiation_lux': 30243.0, 'solarradiation_perceived': 90.0, 'windchill': None}</details>

**To Reproduce**
Just install ecowitt2mqtt addons on Hassio

**Expected behavior**
No Warning

**Comment by bachya** [comment]
This is an upstream "issue" (https://github.com/sbtinstruments/asyncio-mqtt/issues/29) that basically means we're getting congestion and more data from the Ecowitt than the MQTT broker can handle. Will see if that library plans to handle and if not, will do something here.

**Comment by bachya** [comment]
@edouardkleinhans FYI, I've submitted a PR to add the anti-congestion/backpressure mechanism to `asyncio-mqtt` (https://github.com/sbtinstruments/asyncio-mqtt/pull/101); once it gets merged, I will add the latest version here.
