### ISSUE TITLE
Support for Lightning Detection Sensor WH57

### ISSUE THREAD

**Issue by chrisbertsch** [bachya/ecowitt2mqtt#105]
**Enhancement Request**

I am running ecowitt2mqtt version 2022.01.0 with a WH57 lightning sensor and I get the following messages in my logs. The battery sensor is also reported incorrectly due to value not being a simple 0 or a 1 as the other batteries report. I also noticed that Home Assistant does not have units associated with these entries which I  expect is due to no entity description being found.

**ecowitt2mqtt Log:**

```
INFO:ecowitt2mqtt:No entity description found for key: lightning_num
INFO:ecowitt2mqtt:No entity description found for key: lightning
INFO:ecowitt2mqtt:No entity description found for key: lightning_time
```

**Example Data:**

```
lightning_num=0&lightning=20&lightning_time=1642720268&wh57batt=5
```

**Entities**

Values for the WH57 entries based on data I have seen and research on forums.

- lightning_num: integer, daily lightning count
- lightning: integer, value range 0 to 50, distance from detected lightning strike always in km
- lightning_time: integer, time of last detected lightning strike as Unix epoch UTC
- wh57batt: integer, value range 1 to 5 with 1 being low battery

**Comment by bachya** [comment]
Thanks, @chrisbertsch! I'll get working on an enhancement PR. Curious if you also see any `Unknown device; please report it at https://github.com/bachya/ecowitt2mqtt` log messages for this device?

**Comment by chrisbertsch** [comment]
@bachya I searched my logs I did not find anything in regards to `Unknown device`. I did not notice this issue immediately so if it only reports this message once it may have rolled off.

I can try to reproduce if you think this should be present in the logs. Just need to know when I would expect to see this message.

Looking over the code and based on my understanding is that the message is shown if a device is not present in [DEVICE_DATA](https://github.com/bachya/ecowitt2mqtt/blob/2f13c01a548cc57062fe5b86dc4371b189003ef8/ecowitt2mqtt/device.py#L11-L17). I am using a GW1100 to collect the data from the WH57 so if my understanding is correct I would have not triggered the `Unknown device` log message.

**Comment by bachya** [comment]
> Looking over the code and based on my understanding is that the message is shown if a device is not present in DEVICE_DATA. I am using a GW1100 to collect the data from the WH57 so if my understanding is correct I would have not triggered the Unknown device log message.

Got it, didn't realize you were using a GW1100. 👍 

I'll be in touch!

**Comment by bachya** [comment]
@chrisbertsch I'd like to split this into two separate PRs:

1. Lightning data
2. Your type of battery

...and have you test each, if you're willing?

**Comment by chrisbertsch** [comment]
@bachya I am more then willing to test two PRs. Just let me know when they are in a state that you would like me to test.

**Comment by bachya** [comment]
@chrisbertsch Great! Lightning data is ready to test: https://github.com/bachya/ecowitt2mqtt/pull/106

**Comment by bachya** [comment]
This battery translation is going to be interesting. Currently, we attempt to be "automagically helpful" with the two types of battery that we know about:

https://github.com/bachya/ecowitt2mqtt/blob/aeb845444c0d20ec9405cce7bef8e573d4566f68/ecowitt2mqtt/util/battery.py#L8-L21

Unfortunately, this one falls squarely into the automagical-ness that is currently inhabited by binary (on/off) battery sensors, but with no way to distinguish between the two. So, we'll need to have a workaround.

A couple of ideas:

1. Implement some sort of "how should we translate your battery sensors?" environment variable. Makes it more of a configuration issue, but not great because (a) what would a sensible default be? and (b) this will affect _every_ battery (what if the Ecowitt is picking up more than one type)?
2. Maintain the current logic and implement some sort of mapping – e.g., "If you have a battery sensor named XYZ, treat it as a binary battery."

I like 2 because it keeps the automagical-ness in place and allows for an override (albeit in code) if needed.

Thoughts @chrisbertsch?

**Comment by chrisbertsch** [comment]
@bachya So the simplest and maybe good enough might be to flip the logic of your if statement to the following. So when the value is 1 for the WH57 it would report as LOW but anything else would be considered OK. Though I do believe for the WH57 a value of 0 or 1 is consider LOW. But if someone is trying to replace a battery before it depletes completely then replacing the battery with a value of 1 might be sufficient.

```python
     if value == 1: 
         return BATTERY_STATE_ON
     return BATTERY_STATE_OFF
```

I found some additional documentation on the binary/telent protocol which sheds some insight on expected values linked below.

[Telnet Protocol](https://help.ambientweather.net/help/telnet-protocol/)

It does seem that a small subset of sensors report battery status in this 3rd way with a value ranging 0 to 5 which equates to battery percentage from 0 to 100% with 1 being 20%. Per the ecowitt app and website I see a battery indicator icon with 5 battery bars. So it appears multiple sensors report the battery in this manner with the potential of future sensors also reporting in the same manner. To be feature complete I would think we would need to be able to convert this to a battery percentage. The simplest way I can think of  is having a device/sensor list to reference to determine this 3rd type assuming the sensor name will always be prefixed. This is not ideal for maintainability as the list could expand over time compared to your current logic that is beautifully simple.

**Sensors reporting battery as a level 0-5 with values <=1 for Battery Low.**

- WH41
- WH45
- WH55
- WH57
