### ISSUE TITLE
Publish data as structured mqtt topic

### ISSUE THREAD

**Issue by mti-sk** [bachya/ecowitt2mqtt#1053]
Hello,
I would like to request the possibility to publish data in MQTT in a structure.
The project now publishes all parameters in one Topic, I would call it flat. Topic directly contains parameters. This way of storing data creates problems for post-processing, for example in the OpenHAB project. I have not yet figured out how to extract individual parameters. OpenHAB makes easier use of the mqtt topic structure.
I would suggest adding a new parameter something like mqtt_struct <= ( flat | tree)
flat - default, current functionality (all values ​​in one topic)
tree or struct - new functionality of publishing data into a structure (each data as a separate structured mqtt topic)
Now I will explain the processing from OpenHAB's point of view:
I have a structure:
> mqtt
----------> living_room
-------------------------------> thermometer
-------------------------------------------------- ----> temp =24
-------------------------------------------------- ----> humidity=60
If I want to pass the temperature, I use the mqqt path in OpenHAB: mqtt/living_room/thermometer/temp. This topic will directly return a single value of 24°C.
But this is not possible with ecowitt2mqtt, because the project only publishes one topic with all the data. Topic ecowitt2mqtt returns JSON {"runtime": 1007.0, "baromabs": 1005, "temp": 25.38}
The only way to process the data is to parse it using JSONPATH, but as I already wrote, in OpenHAB so far without success (for me).
For OpenHAB, this structure would be more suitable:
> ecowitt2mqtt
----------------------->runtime=1007.0
------------------------>baromabs=1005
----------------------->temp=1005

Best regards

MQTT_Explorer example
![obrazek](https://github.com/user-attachments/assets/1cdc832c-cc91-42fc-9406-ea3272f4777f)

**Comment by endreszabo** [comment]
I have a script that does exactly that. It takes a json and distributes its 
data in the way you described.

as per the KISS principle you should be using my script.

--
Endre

**Comment by bachya** [comment]
I agree with @endreszabo's overall philosophy: I don't think this library should be responsible for a generic DSL that outputs arbitrary data structures.

`ecowitt2mqtt` was designed around the concept of separate "publishers" being responsible for outputting gateway data in an appropriate single format: `TopicPublisher` outputs the gateway data directly to the broker, `HomeAssistantDiscoveryPublisher` outputs the gateway data according to the Home Assistant MQTT Discovery spec, etc. Therefore, I think a more appropriate approach would be to create a new publisher that outputs gateway data according to the openHAB spec.

**Comment by mti-sk** [comment]
Ok
