### ISSUE TITLE
Binary sensors in Home Assistant now require uppercase

### ISSUE THREAD

**Issue by danielsmith89** [bachya/ecowitt2mqtt#108]
**ecowitt2mqtt version**
2022.01.0

**Describe the bug**
Binary sensors since Home Assistant require states in uppercase to work correctly. The file battery.py in util requires updating.

I should probably note, this could be a bug in Home Assistant so have also reported here: https://github.com/home-assistant/core/issues/65640

**Comment by bachya** [comment]
Can you share where you're seeing that? In the latest HASS dev branch, those constants are still lowercase:

https://github.com/home-assistant/core/blob/ac7662c82d8ec9365eb0d62a7aba3218713433a2/homeassistant/const.py#L306-L307

**Comment by danielsmith89** [comment]
From what I can gather, it's a common bug with MQTT in 2022.2, so I don't think it's something you need to fix with this integration, but basically, as soon as I updated battery.py to ON and OFF respectively it started working again.

**Comment by bachya** [comment]
Got it. Let's see how that unfolds; we'll keep this open in the meantime. Thanks!

**Comment by danielsmith89** [comment]
Hi @bachya, I've just had this reply on the HA issue, and it be honest it's gone over my head a little bit, do you understand that this means?

> The configuration for the MQTT binary sensor does not specify a value template or payloads for ON or OFF.
The default payloads are "ON" and "OFF", i.e. capital letters, both on 2021.12.x and in 2022.2.x.
If the binary sensor receives "on" or "off", it will just be ignored.

Are you sure the binary sensor actually worked in 2021.12.x?

I think it ignored the "off" payload there too but the issue went unnoticed because binary sensors in 2021.12.x defaulted to the state "off", whereas they starting with 2022.2.x will default to state "unknown" instead.
