### ISSUE TITLE
Support Home Assistant Long Term Statistics

### ISSUE THREAD

**Issue by chrisbertsch** [bachya/ecowitt2mqtt#110]
**ecowitt2mqtt version**
2022.01.0

**Describe the solution you'd like**
Add support for [Long Term Statistics](https://data.home-assistant.io/docs/statistics/) in Home Assistant that can then be used with the [Statistics Graph Card](https://www.home-assistant.io/lovelace/statistics-graph/).

[Home Assistant Statistics](https://data.home-assistant.io/docs/statistics/)
[Sensor Entity Long Term Statistics](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)

I don't think we need this on all sensors such as battery. I am not sure if this should be user configurable to reduce database growth. It appears today Home Assistant does not have a retention policy for long term statics so it may be undesirable to have this enable for all sensors.

I don't believe today ecowitt2mqtt takes into account local time zone but this may needed to support long running totals for such as rain that resets. I believe this will be needed to be able to sync up when it resets the daily, weekly, monthly, and yearly totals which is configured by the device's time zone.

**Comment by bachya** [comment]
This should be fairly straightforward. 👍🏻 Hope you'll be a willing tester as usual?

>I am not sure if this should be user configurable to reduce database growth. It appears today Home Assistant does not have a retention policy for long term statics so it may be undesirable to have this enable for all sensors.

I don't think storage is something to be overly concerned about at this stage: Home Assistant's `recorder` is where users are explicitly describing when data should be purged.

>I don't believe today ecowitt2mqtt takes into account local time zone but this may needed to support long running totals for such as rain that resets. I believe this will be needed to be able to sync up when it resets the daily, weekly, monthly, and yearly totals which is configured by the device's time zone.

This should be handled for us under the hood: when data is transmitted from MQTT to Home Assistant, Home Assistant will understand when that occurred (in UTC). Rationale: l I manage several other HASS integrations and have never had to manually explain when the rollover should occur.

**Comment by bachya** [comment]
@chrisbertsch Want to help test in #111?

**Comment by alexdelprete** [comment]
> @chrisbertsch Want to help test in #111?

Aaron, I noticed all HA entities are missing the `state_class` attribute:

![image](https://user-images.githubusercontent.com/7027842/165842342-73b3d548-d06b-4fcf-bbc3-d3e9f785990a.png)

This is an essential requirement for LT Statistics support:

![image](https://user-images.githubusercontent.com/7027842/165842053-c6c539cf-4b78-4874-896c-3e240586534a.png)

**Comment by bachya** [comment]
@alexdelprete I'm not sure what you're adding to the conversation. If you are merely voicing support for adding this, you'll note in #111 why it has not been merged yet. PRs always welcome!
