### ISSUE TITLE
add HP1000SE as a known device

### ISSUE THREAD

**Issue by BjMaier** [bachya/ecowitt2mqtt#1121]
**Describe the bug**
[Froggit HP1000SE-PRO device](https://www.froggit.de/hp1000se-pro-single-sensor-edition-hp1000se-pro-display-incl-indoor-sensor-dp40-outdoor-temperature-humidity-dp80-rain-sensor-dp300-anemometer.html) is not mapped and therefore set to Unknown on Home Assistant.

**Expected behavior**
I would expect the device info to show the correct Manufacturer (Froggit) and Device name (HP1000SE)

**Screenshots**
![image](https://github.com/user-attachments/assets/7785b734-ecb5-44a6-9acf-b25c1cf7c7f0)

**Comment by bachya** [comment]
Please include verbose logs so I can see how this device is represented by the gateway.

**Comment by BjMaier** [comment]
```
/ $ nc -l -p 8081
POST data/report HTTP/1.1
HOST: 192.168.0.100
Connection: Close
Content-Type: application/x-www-form-urlencoded
Content-Length: 563

PASSKEY=6A1123454123454E5C12345A7EE95A3&stationtype=EasyWeatherV1.6.1&dateutc=2024-10-05+10:26:43&tempinf=74.8&humidityin=50&baromrelin=28.704&baromabsin=28.704&tempf=51.6&humidity=85&winddir=75&winddir_avg10m=84&windspeedmph=0.9&windspdmph_avg10m=1.6&windgustmph=3.4&maxdailygust=6.9&rainratein=0.000&eventrainin=0.098&hourlyrainin=0.000&dailyrainin=0.004&weeklyrainin=0.827&monthlyrainin=0.807&yearlyrainin=27.488&solarradiation=215.31&uv=2&temp1f=59.4&humidity1=80&wh65batt=0&wh68batt=1.56&wh25batt=0&wh26batt=0&batt1=0&freq=868M&model=HP1000SE-PRO_Pro_V1.7.6
```
