### ISSUE TITLE
entity no longer has a state class

### ISSUE THREAD

**Issue by babstar99** [bachya/ecowitt2mqtt#1159]
**Home Assistant version**
Core 2024.10.3
Supervisor 2024.10.3
Operating System 13.2
Frontend 20241002.3

**ecowitt2mqtt version**
Current version: 2024.10.0

**Describe the bug**
Home assistant shows the error:
> The entity no longer has a state class
> We have generated statistics for 'WS2900 beaufortscale' (sensor.beaufortscale) in the past, but it no longer has a state class, therefore, we cannot track long term statistics for it anymore.
> 
> Statistics cannot be generated until this entity has a supported state class.
> If the state class was previously provided by an integration, this might be a bug. Please report an issue.
> If you previously set the state class yourself, please correct it. [The different state classes and when to use which can be found in the developer documentation.](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics)
> If the state class has permanently been removed, you may want to delete the long term statistics of it from your database.
> Do you want to permanently delete the long term statistics of sensor.beaufortscale from your database?

**To Reproduce**
Installed via the ecowitt2mqtt Home Assistant integration

**Screenshots**
<img width="605" alt="image" src="https://github.com/user-attachments/assets/39009eb6-8578-4ede-a65e-c79a18e65ab3">

**Expected Behaviour**
State class updated to enable long term statistics

**Comment by bachya** [comment]
This is not a bug. The Beautfort Class sensor does not satisfy [the requirements for any Home Assistant state class](https://developers.home-assistant.io/docs/core/entity/sensor/#long-term-statistics) (because it is not a numeric value). You can safely delete long-term statistics for this entity.
