### ISSUE TITLE
TypeError in Lightning sensor support

### ISSUE THREAD

**Issue by smarthall** [bachya/ecowitt2mqtt#118]
**ecowitt2mqtt version**
`2022.04.0`

**Describe the bug**
The data coming into the lightning sensor needs to be converted from a string to a float before it is passed to the `calculate_distance` function. This should be fixable by changing the `val` to `float(val)` on this line: https://github.com/bachya/ecowitt2mqtt/blob/dev/ecowitt2mqtt/data.py?rgh-link-date=2022-04-19T09%3A38%3A53Z#L58

**To Reproduce**
1. Install version `2022.04.0`
2. Send some example lighting data, see this comment: https://github.com/bachya/ecowitt2mqtt/issues/105#issue-1111203195

**Expected behavior**
The data be processed without error

**Additional context**
Reported by a user to the downstream home assistant addon: https://github.com/smarthall/hassio-addons/pull/9

**Comment by bachya** [comment]
@smarthall FYI, just cut [2022.04.1](https://github.com/bachya/ecowitt2mqtt/releases/tag/2022.04.1) – the Docker image should be built in the next 5-10 minutes (https://github.com/bachya/ecowitt2mqtt/actions/runs/2191206025).
