### ISSUE TITLE
Allow selecting imperial or metric units for submission to Home Assistant

### ISSUE THREAD

**Issue by smarthall** [bachya/ecowitt2mqtt#12]
**ecowitt2mqtt version**
0.1.1

**Describe the solution you'd like**
Many of the units that the weather station reports in aren't used in my region (Australia). I'd love to have them converted to nicer ones before they are sent to Home Assistant (or MQTT).

Units that should be changed for metric regions:
Temperature: °C
Wind: km/h
Rain: mm
Barometer: hPa

I'd love to take a shot at tackling this one, if I could get some guidance on how you think this might fit in.

**Comment by bachya** [comment]
Thanks for the idea, @smarthall! I'd love for you to take a stab at it. At first glance, I think a config option/environment variable for unit type should be required. Not sure where in the current architecture the logic would fit – perhaps `ecowitt2mqtt/data.py`? – but open to you trying and we can collaborate from there.

**Comment by dbird86** [comment]
I just discovered this tool and I too am from Australia so would like the metric options.

**Comment by dbird86** [comment]
I just discovered this tool and I too am from Australia so would like the metric options.

**Comment by zackbcom** [comment]
Looks like we might be able to infer the metrics base on the passed in key. Example `tempinf`
from the payload:
````
{
  PASSKEY: 'PASSKEY',
  stationtype: 'GW1000B_V1.6.3',
  dateutc: '2020-10-31 02: 44: 13',
  tempinf: '78.6',
  humidityin: '48',
  baromrelin: '29.258',
  baromabsin: '29.258',
  tempf: '50.5',
  humidity: '61',
  winddir: '274',
  windspeedmph: '0.00',
  windgustmph: '1.12',
  maxdailygust: '1.12',
  solarradiation: '0.00',
  uv: '0',
  rainratein: '0.000',
  eventrainin: '0.000',
  hourlyrainin: '0.000',
  dailyrainin: '0.000',
  weeklyrainin: '0.051',
  monthlyrainin: '0.051',
  yearlyrainin: '0.051',
  totalrainin: '0.051',
  soilmoisture1: '0',
  wh65batt: '0',
  soilbatt1: '1.6',
  freq: '915M',
  model: 'GW1000_Pro',
}
````

**Comment by bachya** [comment]
Let's split this work into multiple PRs:

- [ ] Temperature
- [ ] Wind
- [ ] Rain
- [ ] Barometer

**Comment by bachya** [comment]
Alright – the above PRs lay add metric support for temperature, wind, rain, and barometric pressure (as well as provide a framework for any future-such additions). Going to close this issue off for now, but if more work should arise, we can re-open.
