### ISSUE TITLE
Configurable Prefix for HA entities

### ISSUE THREAD

**Issue by alexdelprete** [bachya/ecowitt2mqtt#127]
**ecowitt2mqtt version**
2022.4.3

**Describe the solution you'd like**
a configuration parameter to set a prefix for HA entities or, in alternative, the name of the gateway (GW1000 or GW2000).

Since I have 3 weather stations, the entities names are starting to create some confusion, it's important to distinguish them.

For example, the entity ID in the following image would become `sensor.prefix_baromabs` or `sensor.gw2000a_baromabs`.

![image](https://user-images.githubusercontent.com/7027842/165838784-5295545b-29a4-4bc8-831c-882a022c1b86.png)

**Comment by bachya** [comment]
After chewing on it, I think the right way is to automatically prepend the `PASSKEY` field (falling back to `stationtype` if it doesn't exist) for each entity ID. This method will produce some wacky entity IDs (since `PASSKEY` is a random string). Still, we can guarantee their uniqueness – and with device registry support, users will know which entity belongs to which device.

Let me put together a PR, and you can test it?

**Comment by alexdelprete** [comment]
you don't like making it configurable, like you did for the mqtt topic and the rest?

in any case, I doubt users have more than 1 gateway of the same model, it wouldn't make sense. I have two gateways, 1 GW1000A and 1 GW2000A. But they provide the same data, so I will dismiss the GW1000A.

Another idea: the device model (GW2000A in my case) with last 3 chars of the passkey. Less wacky. :)

**Comment by bachya** [comment]
> you don't like making it configurable, like you did for the mqtt topic and the rest?

How would that work? I supposed we could make an environment variable that maps some data to a user-defined prefix, but how would the user easily be able to find that data?

> Another idea: the device model (GW2000A in my case) combined with last 2 chars of the passkey. Less wacky. :)

I like that, but with a few more chars (just in case) – say, 4. So, in the case of this payload:

```json
{
    "PASSKEY": "CYYYXXXXX057B",
    "stationtype": "GW2000A_V2.1.4",
    "runtime": "436796",
    "dateutc": "2022-04-20 19:14:47",
    "tempinf": "72.9",
    "humidityin": "56",
    "baromrelin": "29.870",
    "baromabsin": "29.509",
    "tempf": "59.7",
    "humidity": "65",
    "winddir": "327",
    "windspeedmph": "2.24",
    "windgustmph": "3.80",
    "maxdailygust": "17.45",
    "solarradiation": "0.00",
    "uv": "0",
    "rainratein": "0.000",
    "eventrainin": "0.000",
    "hourlyrainin": "0.000",
    "dailyrainin": "0.000",
    "weeklyrainin": "0.000",
    "monthlyrainin": "0.736",
    "yearlyrainin": "3.909",
    "rrain_piezo": "0.000",
    "erain_piezo": "0.063",
    "hrain_piezo": "0.000",
    "drain_piezo": "0.075",
    "wrain_piezo": "0.075",
    "mrain_piezo": "0.941",
    "yrain_piezo": "4.114",
    "ws90cap_volt": "5.2",
    "ws90_ver": "115",
    "temp1f": "71.2",
    "humidity1": "61",
    "temp2f": "71.2",
    "humidity2": "58",
    "temp3f": "70.5",
    "humidity3": "61",
    "temp4f": "73.0",
    "humidity4": "58",
    "temp5f": "70.7",
    "humidity5": "69",
    "temp6f": "72.7",
    "humidity6": "58",
    "temp7f": "67.1",
    "humidity7": "54",
    "temp8f": "68.0",
    "humidity8": "56",
    "soilmoisture1": "53",
    "soilmoisture2": "57",
    "soilmoisture3": "59",
    "soilmoisture4": "49",
    "soilmoisture5": "52",
    "pm25_ch1": "21.0",
    "pm25_avg_24h_ch1": "16.3",
    "tf_co2": "62.2",
    "humi_co2": "61",
    "pm25_co2": "4.9",
    "pm25_24h_co2": "7.5",
    "pm10_co2": "6.1",
    "pm10_24h_co2": "7.8",
    "co2": "455",
    "co2_24h": "473",
    "lightning_num": "13",
    "lightning": "1",
    "lightning_time": "1650475037",
    "wh80batt": "3.28",
    "batt1": "0",
    "batt2": "0",
    "batt3": "0",
    "batt4": "0",
    "batt5": "0",
    "batt6": "0",
    "batt7": "0",
    "batt8": "0",
    "soilbatt1": "1.4",
    "soilbatt2": "1.3",
    "soilbatt3": "1.3",
    "soilbatt4": "1.3",
    "soilbatt5": "1.3",
    "pm25batt1": "3",
    "wh57batt": "3",
    "co2_batt": "6",
    "wh90batt": "3.22",
    "freq": "868M",
    "model": "GW2000A",
}
```

...the prefix would be `gw2000a_057B`.

Thoughts?

**Comment by alexdelprete** [comment]
> How would that work? I supposed we could make an environment variable that maps some data to a user-defined prefix, but how would the user easily be able to find that data?

a config parameter, in my case I'm using docker compose env variables, but it could be a cmdline parameter for other versions of ecowitt2mqtt.

> --hass_entity_prefix "GW2000_HOME1"

or in case of docker:

```
    environment:
      MQTT_TOPIC: ecowitt2mqtt/GW2000A
      ENDPOINT: /data/report
      HASS_DISCOVERY: true
      HASS_DISCOVERY_PREFIX: homeassistant
      HASS_ENTITY_PREFIX: "GW2000_HOME1"
```

Then use that as a prefix for the entities, and also when creating the device in the homeassistant discovery topic, I noticed right now you are using PASSKEY. If the user doesn't configure this parameter/variable, then use device model + last 4 chars of passkey.

![image](https://user-images.githubusercontent.com/7027842/165862221-1b6d0fd7-d232-4048-aa32-69c4d6ae6a32.png)

**Comment by alexdelprete** [comment]
If there's no PASSKEY, and user doesn't configure the optional parameter, `model` can be used.

**Comment by bachya** [comment]
What if a user points multiple Ecowitt devices at the same instance of `ecowitt2mqtt`?

**Comment by alexdelprete** [comment]
ecowitt2mqtt maps an ecowitt gateway, and like I said it doesn't have much sense having multiple gateways for the same data (they would both receive the same data from the same sensors).

unless you are thinking about a scenario where I have multiple sites, and all gateways report to a central ecowitt2mqtt instance. In that case we need PASSKEY to distinguish them. But we must be sure that PASSKEY is always present in the data.

**Comment by bachya** [comment]
Got it; thanks for checking me on that. In that case, I like your idea of an environment variable. If the user omits it, they should take whatever entity IDs HASS gives them (vs. doing something more complex) – we can at least start there and see what people think.

**Comment by alexdelprete** [comment]
btw: with how it is structured now, ecowitt2mqtt doesn't support multiple gateways because it only manages one mqtt topic: `mqtt_topic='ecowitt2mqtt/GW2000A'`

but with HA discovery turned on, it can support multiple gateways because right now the topic created is the passkey. if the environment variable is configured, it should be used as prefix and also for the topic under homeassistant main topic.

If you use `model` (from the data) + 4 chars of passkey, everything would work ok, also the multiple gateways reporting to a central ecowitt2mqtt instance.

I just noticed that ecowitt uses a similar approach to create the initial AP wlan to configure the gateway, but it uses 4 chars of the MAC address.

![image](https://user-images.githubusercontent.com/7027842/165865178-13ce135f-1b17-4662-9afe-7efb2d585078.png)

[END OF BRAINSTORIMING SESSION] :)

Thank you Aaron.
