### ISSUE TITLE
Errore Installazione

### ISSUE THREAD

**Issue by saviothecnic** [bachya/ecowitt2mqtt#131]
Se provo a installarlo ho quest' errore

pi@RaspDomoticz:~ $ pip install ecowitt2mqtt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ecowitt2mqtt
 Could not find a version that satisfies the requirement ecowitt2mqtt (from versions: )
![ErroreInstallazione](https://user-images.githubusercontent.com/6697807/168082267-a4cc14bb-711b-4ea6-858e-f588978d4377.jpg)
No matching distribution found for ecowitt2mqtt

**Comment by bachya** [comment]
What version of Python and pip are you using?

**Comment by saviothecnic** [comment]
thanks i solved it by launching the command pip3 install ecowitt2mqtt

Then it gave me error port 8080 already used because on the same raspberry I have domoticz and I moved to port 8090 and now everything seems to work with this string I write it maybe it is also useful to others

ecowitt2mqtt --mqtt-broker 192.168.1.20 --port 8090 --mqtt-topic=ecowitt2mqtt/meteo --mqtt-username mosquitto --mqtt-password MiaPass

Now I want to make it always start up as I should
do I add this string in rc.local?

Thanks

**Comment by bachya** [comment]
Glad to hear you solved your issue. RE: automatic startup, this is covered in the docs: https://github.com/bachya/ecowitt2mqtt#running-in-the-background

**Comment by saviothecnic** [comment]
OK, thanks a lot
Last question on both the app and the string I set
metric units but known the temperature is read in imperial
INFO: ecowitt2mqtt: Published to ecowitt2mqtt / meteo: {'tempin': 71.2, 'humidityin': 65, 'baromrel': 29.947, 'baromabs': 29.708, 'temp': 65.7

**Comment by bachya** [comment]
What is your question?

**Comment by saviothecnic** [comment]
> What is your question?

sorry if I explained myself wrong
my question is i put it in the string
--input-unit-system metric --output-unit-system metric
So I should get metric data but still get the temperature with imperial value
in the example on temepratura 71,2 which certainly are not ° C

**Comment by bachya** [comment]
Got it; thanks! In my experience, every Ecowitt device I've tried reports its units in imperial – this means that if you wanted to output them in metric, you'd need:

```
ecowitt2mqtt --mqtt-broker 192.168.1.20 --port 8090 --mqtt-topic=ecowitt2mqtt/meteo --mqtt-username mosquitto --mqtt-password MiaPass --input-unit-system imperial --output-unit-system metric
```

If you try that, does the data look correct?

**Comment by saviothecnic** [comment]
> --input-unit-system imperial --output-unit-system metric

Yes, thank you, this was the problem so the data is correct
Excuse me but having set the data in metric on the APP
I didn't think you should set imput to imperial

**Comment by bachya** [comment]
Glad it's working now!

**Comment by saviothecnic** [comment]
> Glad to hear you solved your issue. RE: automatic startup, this is covered in the docs: https://github.com/bachya/ecowitt2mqtt#running-in-the-background

Excuse my little knowledge of raspbian commands I created the files with

sudo nano /etc/systemd/system/ecowitt2mqtt.service

It is edited as shown in the photo below
![immagine](https://user-images.githubusercontent.com/6697807/168292473-b7d04b33-1b4f-40cc-9a76-0ea29d8df862.png)

I launch the command to see if everything is ok

systemctl status ecowitt2mqtt.service

but i have this error i understand that something is missing in some folder but i don't understand where i am wrong

```
 ecowitt2mqtt.service - ECOWITT2MQTT daemon
   Loaded: bad-setting (Reason: Unit ecowitt2mqtt.service has a bad unit file setting.)
   Active: inactive (dead)

mag 13 15:04:16 RaspDomoticz systemd[1]: /etc/systemd/system/ecowitt2mqtt.service:6: Executable "ecowitt2mqtt" not found in path "/usr/local/sbin:/usr/local/bin:/usr/sb
lines 1-5/5 (END)

```

**Comment by bachya** [comment]
I am not able to provide general Linux support, unfortunately, as it is outside the scope of this library. That said, the logs explain what is going on:

```
Executable "ecowitt2mqtt" not found in path "/usr/local/sbin:/usr/local/bin:/usr/sbin
```

So, I would put the full path to `ecowitt2mqtt`. You can find this by running:

```
$ type ecowitt2mqtt
```

**Comment by saviothecnic** [comment]
I'm sorry I can understand that you cannot give support
for raspian basics and I'm leaving the topic
I'll try to figure out where I'm wrong anyway this is what I have in response to the command you advised me to run

Ecowitt2mqtt è /home/pi/.local/bin/ecowitt2mqtt

**Comment by bachya** [comment]
Can you post the error you now receive?

**Comment by saviothecnic** [comment]
![immagine](https://user-images.githubusercontent.com/6697807/169552493-79c493b5-355d-425c-96b9-626cc5c5f5d6.png)

**Comment by bachya** [comment]
Your service is still looking for `ecowitt2mqtt` in the path of the user running that service (and not finding it).

**Comment by saviothecnic** [comment]
> Your service is still looking for `ecowitt2mqtt` in the path of the user running that service (and not finding it).

Yes I understand this
but I don't understand how I can tell him where to find it

I thought it was enough to enter the path in ecowitt2mqtt.service
but it seems that there is not the right place to indicate it
