### ISSUE TITLE
Update Readme to correctly describe "Unit System"

### ISSUE THREAD

**Issue by JaseZa** [bachya/ecowitt2mqtt#132]
It seems the way unit systems are handled has changed since you wrote the readme - now uses `Unit-system` instead of `input-unit-system` and `output-unit-system`. Might help some others if the readme is updated as it took me quite a while to figure out!

Thanks for a great project!

**Comment by bachya** [comment]
We definitely still use `input-unit-system` and `output-unit-system`:

https://github.com/bachya/ecowitt2mqtt/blob/d7a30f7364dc2499a57dbea717d9b00235c01d2c/run.sh#L54-L60

https://github.com/bachya/ecowitt2mqtt/blob/d7a30f7364dc2499a57dbea717d9b00235c01d2c/ecowitt2mqtt/main.py#L117-L130

Can you provide more info?

**Comment by JaseZa** [comment]
Thanks for the response - should have given more info from the start!

I'm running ecowitt2mqtt through a docker container. It had been running continuously for nearly a year with the following environment variables:

MQTT_BROKER
MQTT_USERNAME
MQTT_PASSWORD
HASS_DISCOVERY=TRUE
PORT

It had worked perfectly from the start and in the correct units matching my Ambient Weather WS-2902C and Ecowitt GW1000 - metric units. Yesterday I had to restart my server and reload your docker container, but this time it would only send the units in imperial for temperature. Nothing had changed on the weather station or Ecowitt. I had done a HA update a couple of days before though - now on the latest 2022.5.4.

I looked through the documentation and found the info about input/output unit system, but after trying every possible combination of those, it still would only ever send the temperature in °F. Going through the debug logs I saw in the logs "unit-system=imperial" and on a whim tried using that as an environment variable but set to metric. Worked perfectly first time! So I assumed this was a change you had made and not documented? Although I see now that isn't the case. Had hoped my query here might help some others if they were also battling.

This is what I'm now running:

sudo docker run -it     
-e MQTT_BROKER=x.x.x.x     
-e MQTT_USERNAME=xxx     
-e MQTT_PASSWORD=xxx     
-e HASS_DISCOVERY=true     
-e LOG_LEVEL=FATAL    
-e UNIT_SYSTEM=metric   
-p 8080:8080     
bachya/ecowitt2mqtt:latest

**Comment by bachya** [comment]
Take a look at [the Docker section of the docs](https://github.com/bachya/ecowitt2mqtt#docker) – specifically, note the last two parameters:

> * `INPUT_UNIT_SYSTEM`: the input unit system to use (`imperial` or `metric`) (default: `imperial`)
> * `OUTPUT_UNIT_SYSTEM`: the output unit system to use (`imperial` or `metric`) (default: `imperial`)

This was changed in [release 2.0.0](https://github.com/bachya/ecowitt2mqtt/releases/tag/2.0.0) (before the library switched to CalVer) and was listed as a breaking change (see #80 for more details).

If you update your environment variables accordingly, does the issue resolve?

**Comment by bachya** [comment]
Got it! No worries at all and glad you got it resolved.
