### ISSUE TITLE
ecowitt2mqtt: error: unrecognized arguments: --hass-entity-id-prefix

### ISSUE THREAD

**Issue by moesizlag** [bachya/ecowitt2mqtt#135]
As per documentation I wanted to change the hass entity id prefix:
`  --hass-entity-id-prefix HASS_ENTITY_ID_PREFIX
                        The prefix to use for Home Assistant entity IDs`

On docker the ENV is just silently ignored it seems, the entity id prefix used in HASS MQTT ends up to be some random looking string. On CLI I get the error:
`ecowitt2mqtt: error: unrecognized arguments: --hass-entity-id-prefix`

**Comment by bachya** [comment]
What version are you using?

**Comment by moesizlag** [comment]
Error occured in 2022.4.3., it does not in 2022.5.0, hence closing this :)

**Comment by bachya** [comment]
Wow! Glad it’s working for you now.
