### ISSUE TITLE
Allow adding to HA via Supervisor (add repository)

### ISSUE THREAD

**Issue by kkellner** [bachya/ecowitt2mqtt#14]
**ecowitt2mqtt version**
n/a

**Describe the solution you'd like**
To increase adoption and make it easier to install, consider allowing ecowitt2mqtt to be added as an add-on via Home Assistant supervisor by "Manage add-on repositories" and adding this github repo URL.

https://developers.home-assistant.io/docs/add-ons/repository/

Example:

![image](https://user-images.githubusercontent.com/9540241/97341677-00cd4b00-184b-11eb-93c6-ebbfee56fd28.png)

Currently if you try to do this, you get:

![image](https://user-images.githubusercontent.com/9540241/97341714-0b87e000-184b-11eb-8281-ab184b3b398a.png)

```
20-10-27 17:48:35 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/acfd5b1a/repository.json: [Errno 2] No such file or directory: '/data/addons/git/acfd5b1a/repository.json'
20-10-27 17:48:35 ERROR (MainThread) [supervisor.store] https://github.com/bachya/ecowitt2mqtt is not a valid add-on repository. 
```

Another 3rd party addon that does this (as an example):
https://github.com/danmed/TasmoBackupV1/blob/master/repository.json
https://github.com/danmed/TasmoBackupV1/tree/master/HA_addon

**Comment by bachya** [comment]
I'm not a user of Home Assistant Supervisor, but am open to anyone submitting a PR for this!

**Comment by smarthall** [comment]
I made an addon for it in my addons repo: https://github.com/smarthall/hassio-addons

Feel free to steal that code for the 'official' one.

**Comment by bachya** [comment]
@smarthall Looking at your example, it seems like my Docker image needs to be included in a _separate_ "repository" repo (rather than the repository stuff being included in _this_ repo) – is that your understanding? If so, would you be interested in being the official HASS add-on repo for us?

**Comment by smarthall** [comment]
It doesn't _need_ to be in a separate repository, however many projects choose to as it pollutes the main repository.

I'm happy for my addon to be blessed as the official add-on. I'll inspire me to keep working on it.

**Comment by bachya** [comment]
Got it. Let's have you be the owner since you (I assume) use Supervisor HASS and can properly look at that side. Much appreciated!

@kkellner See above: https://github.com/smarthall/hassio-addons is your winner.

Going to close this issue for now, but comment if we need to re-open!
