### ISSUE TITLE
81 mqtt:There are pending publish calls every minute

### ISSUE THREAD

**Issue by carlos-sarmiento** [bachya/ecowitt2mqtt#140]
**ecowitt2mqtt version**
Latest Docker version

**Describe the bug**
I'm getting a ton of pending publish calls on my logs. My mqtt server is running on a proper computer so I don't see why they would need to be rate limited. Is there a way to increase the threshold? Or to reduce the frequency data gets reported?

**Screenshots**
```
today at 6:05:24 PM WARNING:mqtt:There are 11 pending publish calls.
today at 6:05:24 PM WARNING:mqtt:There are 12 pending publish calls.
...
today at 6:05:24 PM WARNING:mqtt:There are 80 pending publish calls.
today at 6:05:24 PM WARNING:mqtt:There are 81 pending publish calls.
````
**Additional context**

**Comment by bachya** [comment]
Thanks for the report – I notice the same. I'm in the middle of a pretty large rearchitecture and will look to address this there.
