### ISSUE TITLE
Home Assistant Doesnt Discover Sensor Type Properly

### ISSUE THREAD

**Issue by mike240se** [bachya/ecowitt2mqtt#15]
I'm using the "latest" docker image (0.1.1).  I have HASS Discovery turned on (btw you might want to add example to the docker-compose.dist.yaml file for enabling hass discovery as it took me a few minutes to figure it out) and while everything shows up in HA, it doesnt properly detect the sensor type or unit type.  For example, instead of getting a graph for temp and humidity, i am given colored bars histogram.   Also instead of seeing 90F for temp i see 90.11 and for humidity instead of seeing 70% i see 70.11.  I cant find in the HA MQTT discovery docs how to fix this in HA so i am not sure if this needs to be fixed in ecowitt2mqtt or not, also not sure if this is a bug or feature request, sorry about that.

For example:

This is what I see for humidity: https://i.imgur.com/pFn8Mqh.png
This is what I see for temp (on add-on TH sensors): https://i.imgur.com/g1mwsNf.png
This is what I see for soil moisture sensors: https://i.imgur.com/KtIvqDr.png

THis is what i expect to see (and what i see if i get the data from ambientweather integration instead): https://i.imgur.com/MNhS6ir.png

Same for temp.   

What is interesting, some things work as expected such as this feels like temp: https://i.imgur.com/v98beEI.png and regular outdoor temp: https://i.imgur.com/UAEyQsG.png

EDIT: in the process of making screenshots for this bug report I reallize now the issue seems to be with soil sensors and add-on temp/humidity sensors.   most the rest looks correct so i am thinking this is in fact just a simple bug in the discovery process for these sensors.

Thanks for this project, this is EXCELLENT!  Its so much better than using my ambient weather integration because that is cloud polling and is SLOW and this works so much better for triggering automations since I can control the refresh time.  thanks.

**Comment by bachya** [comment]
Thanks for the report, @mike240se. Based on your last comment:

> EDIT: in the process of making screenshots for this bug report I reallize now the issue seems to be with soil sensors and add-on temp/humidity sensors. most the rest looks correct so i am thinking this is in fact just a simple bug in the discovery process for these sensors.

...I'm guessing that we're missing mappings between field names that you're using and their corresponding icons/units.

I'll copy over the structure I used in the Ambient HASS integration; hang tight and I'll have you test the PR.

**Comment by bachya** [comment]
@mike240se Please test #16 and see if it resolves your issue. There isn't a Docker image for this yet, so you'll have to test using the library itself.

**Comment by mike240se** [comment]
Thanks much! I replaced the 2 files in the PR and things have gotten better but still having a few issues....   

On some of the sensors, I am randomly getting crazy number of decimal places on some of the numbers like 45.154423232332323F for example: https://i.imgur.com/ewliFSB.png

Not sure if you can do anything about that, they flucuate from  2 decimal places to a lot.  Maybe this is a HA issue.  

My add-on temp/humidity sensors all seem to be working correctly now, its odd and I am sure this is a HA thing, but now I get the correct graph but still also get the histogram bar: https://i.imgur.com/jvHEZy2.png  some I still only get the histogram bar:  https://i.imgur.com/ZbSjZUr.png

The soil sensors still seem to be an issue though, they dont show as a % and still show only the histogram graph (and dont show the water-percent icon like the humidity ones do) https://i.imgur.com/I9ujmIX.png

Another thing I noticed is the indoor humidity shows as inches: https://i.imgur.com/aTVWMbW.png

I am trying to figure out how to get rid of all these entities from HA so it will recreate them all, I am thinking that might solve the issue.  The option to delete is grayed out in HA for the entities.

**Comment by mike240se** [comment]
One thing i noticed regarding the soil sensors is in the const.py they are called: soilhum01, soilhum02, etc.  but in my mqtt broker they are soilmoisture1, soilmoisture2, etc.   I dont have soilhum01, etc.   Perhaps this is because I was running it before you made the fix.

**Comment by mike240se** [comment]
Yeah, that was the problem with the soil moisture sensors.   They need to be changed to DATA_POINT_SOILMOISTURE1 and it fixes the issue :)

will try to do a PR

**Comment by zackbcom** [comment]
I left feed back on the Merge of Mike240se to update a few consts names. I can verify after the changes it's working.

**Comment by mike240se** [comment]
There are also some battery sensors that need to be setup for the TH sensors and the soil sensors.   The soil sensors look like this:

https://i.imgur.com/xJ5mw8G.png
```
{
  "availability_topic": "homeassistant/sensor/1624C76D3008011EFEEACBA19A743DC3/soilbatt1/availability",
  "icon": "mdi:server",
  "name": "soilbatt1",
  "qos": 1,
  "state_topic": "homeassistant/sensor/1624C76D3008011EFEEACBA19A743DC3/soilbatt1/state",
  "unique_id": "1624C76D3008011EFEEACBA19A743DC3_soilbatt1",
  "unit_of_measurement": ""
}
```

TH battery: https://i.imgur.com/192hIs4.png

```
{
  "availability_topic": "homeassistant/sensor/1624C76D3008011EFEEACBA19A743DC3/batt2/availability",
  "icon": "mdi:server",
  "name": "batt2",
  "qos": 1,
  "state_topic": "homeassistant/sensor/1624C76D3008011EFEEACBA19A743DC3/batt2/state",
  "unique_id": "1624C76D3008011EFEEACBA19A743DC3_batt2",
  "unit_of_measurement": ""
}
```

**Comment by bachya** [comment]
Thanks for the feedback, @mike240se and @zackbcom. I'll merge #17, then rebase #15 before merging it.

After that, if there is any additional work needed, let's open up individual issues so it's easier to follow (instead of of lumping everything into one issue). Thanks!

**Comment by bachya** [comment]
@mike240se and @zackbcom, the `dev` Docker image (which contains #15 and #17) is [building now](https://github.com/bachya/ecowitt2mqtt/runs/1343435134?check_suite_focus=true) – once it's complete, please pull and confirm whether you're good to go.
