### ISSUE TITLE
Docker fails to start

### ISSUE THREAD

**Issue by yieldhog** [bachya/ecowitt2mqtt#152]
**Describe the bug**
Docker process fails to start on new version, see start error in screenshot

**Screenshots**

<img width="255" alt="Screen Shot 2022-06-08 at 6 42 58 PM" src="https://user-images.githubusercontent.com/3329021/172740740-f7038d16-44bb-4312-9ed3-03b356717711.png">

**Additional context**
Have been successfully using all prior versions, great find. This is run on a Synology if that matters, but, all prior containers worked well. Thank you from Denver.

**Comment by bachya** [comment]
This library no longer uses `run.sh`, so that's the issue. I don't have a Synology; how are you creating the Docker container?

**Comment by yieldhog** [comment]
> This library no longer uses `run.sh`, so that's the issue. I don't have a Synology; how are you creating the Docker container?

Ahh, I had upgraded the container -- appears to work after deleting completely and re-creating. No issues!
