### ISSUE TITLE
"No calculator found for tf_ch1" for WN34L

### ISSUE THREAD

**Issue by jeremykuhlman** [bachya/ecowitt2mqtt#172]
After the recent update in #144, the WN34L Liquid Temperature Sensor (`tf_ch1`) looks to no longer be reporting.   Seeing the following in the logs for the docker container.  It was previously working before this release (although I believe it was missing the `unit of measurement` property).

Seeing in this in the docker container's logs:
```
2022-06-10 17:46:14,638 | ecowitt2mqtt | DEBUG | No calculator found for tf_ch1
2022-06-10 17:46:14,639 | ecowitt2mqtt | DEBUG | Calculator found for tf_batt1: calculate_battery (key: tf_batt1, value: 1.6)
2022-06-10 17:46:14,639 | ecowitt2mqtt | WARNING | Skipping tf_ch1 due to error: No entity description
```

**Comment by bachya** [comment]
Can you please provide the entire raw payload from the logs?

**Comment by jeremykuhlman** [comment]
Attached is the output from the log files after setting `ECOWITT2MQTT_DIAGNOSTICS: "true" as requested.

[Ecowitt2MQTT_Diagnostics.txt](https://github.com/bachya/ecowitt2mqtt/files/8885759/Ecowitt2MQTT_Diagnostics.txt)

**Comment by jeremykuhlman** [comment]
Thanks for the quick turnaround on this issue - seeing the temperature value coming across now for my sensor in HA!

Briefly looking at the files changed in commit #174, I noticed that it _appears_ that it is only looking for a value for a single/first water temperature sensor ([`tf_ch1`](https://github.com/bachya/ecowitt2mqtt/blob/90cd1a790142cecea901506616fe96db527f09b9/ecowitt2mqtt/const.py#L100)).  However I think the Ecowitt Wireless Weather Station Gateway GW1100 supports up to 8 of these (`tf_ch2`, `tf_ch3`, etc.)  If someone where to have more than one, then I believe their values wouldn't come across. 

I do see in the [const.py](https://github.com/bachya/ecowitt2mqtt/blob/90cd1a790142cecea901506616fe96db527f09b9/ecowitt2mqtt/const.py#L117) file there are specific Data Points for all 8 possible battery levels for these devices.

As I mentioned though, I didn't really dig in to the code a whole lot so you might be handling this elsewhere and if so, I apologize!

**Comment by bachya** [comment]
Thanks for letting me know!

My original solution would have covered all of those automatically, but unfortunately, the extremely scattershot way that Ecowitt devices can be named necessitated something more simplistic. I'll update everything with your info.

Thanks again!

**Comment by jeremykuhlman** [comment]
You betcha - definitely appreciate the hard work you have put into this!
