### ISSUE TITLE
Missing entity descriptions for leak sensors and leaf wetness

### ISSUE THREAD

**Issue by aklaiber82** [bachya/ecowitt2mqtt#177]
Hi All -

First, awesome work!!!!  I am not smart enough  yet to fix this issue but in old releases (around April) the leaf wetness and leak sensors worked fine.  In the most recent release and the dev release they seem to have issues:

2022-06-14 23:54:55,144 | ecowitt2mqtt | WARNING | Skipping "leak_ch1" due to error: No entity description
2022-06-14 23:54:55,144 | ecowitt2mqtt | WARNING | Skipping "leak_ch2" due to error: No entity description
2022-06-14 23:54:55,145 | ecowitt2mqtt | WARNING | Skipping "leak_ch3" due to error: No entity description
2022-06-14 23:54:55,145 | ecowitt2mqtt | WARNING | Skipping "leak_ch4" due to error: No entity description
2022-06-14 23:54:55,148 | ecowitt2mqtt | WARNING | Skipping "leafwetness_ch1" due to error: No entity description

Hoping this is an easy fix but since it used to work.  Thanks for all the updates on this and especially for the recent fix to the lightning counts and today's fix for the multiple tf temperature probes.  I really appreciate this a ton!

**Comment by bachya** [comment]
Thanks for the info! Can you send me a diagnostics dump as mentioned in the readme? That'll help me get this addressed quickly. Appreciate it!

**Comment by aklaiber82** [comment]
I really wish I knew more.  I am running it in docker and can't seem to figure out how to generate this.  I'm really sorry.  I do know that it worked in the 2022.5.0 release and broke when updating to the 2022.6.0 one.

**Comment by bachya** [comment]
No problem! Do this for me: set the `ECOWITT2MQTT_VERBOSE` environment variable to `true`. Then, after you restart your container, the logs will contain the info I need.

**Comment by bachya** [comment]
(FYI, #178 will "fix" things in that you'll be able to see those sensors again – but if you can get me those verbose Docker logs, we can ensure that they get units, etc.)

**Comment by aklaiber82** [comment]
This is for the current dev version commit from today.  Let me know if you need more.
[verbose_log_v1.txt](https://github.com/bachya/ecowitt2mqtt/files/8904835/verbose_log_v1.txt)

**Comment by bachya** [comment]
Perfect. Thanks!
