### ISSUE TITLE
Calculations can cause keyerrors if keys not present

### ISSUE THREAD

**Issue by ryanho87** [bachya/ecowitt2mqtt#19]
**ecowitt2mqtt version**
Latest 0.1.1

**Describe the bug**
Calculations will result in KeyErrors if the payload from ecowitt does not have the key value pairs necessary for the calculations.  If a system does not have a sensor for wind, ecowitt omits the key instead of including it as a zero value.

```
INFO:aiohttp.access:10.0.0.50 [04/Nov/2020:06:31:44 +0000] "POST /data/report HTTP/1.1" 500 244 "-" "-"
DEBUG:ecowitt2mqtt:Received data from Ecowitt device: {'PASSKEY': 'C0B95A3A9FB7BEA5D6A6D6E3060B9A7F', 'stationtype': 'GW1000B_V1.6.3', 'dateutc': '2020-11-04 06:32:14', 'tempinf': '73.0', 'humidityin': '50', 'baromrelin': '29.689', 'baromabsin': '29.689', 'tempf': '51.8', 'humidity': '94', 'temp1f': '68.72', 'humidity1': '54', 'soilmoisture1': '38', 'wh26batt': '0', 'batt1': '0', 'soilbatt1': '1.5', 'freq': '915M', 'model': 'GW1000_Pro'}

ERROR:aiohttp.server:Error handling request

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/src/ecowitt2mqtt/routes.py", line 21, in async_respond_to_ecowitt_data
    data = process_data_payload(data)
  File "/usr/src/ecowitt2mqtt/data.py", line 23, in process_data_payload
    wind_speed = float(data[DATA_POINT_WINDSPEEDMPH])
KeyError: 'windspeedmph'
```

It would be nice if this was configurable via an environment variable for the docker image.

**Comment by bachya** [comment]
@ryanho87 Can you describe what you mean by this?

> It would be nice if this was configurable via an environment variable for the docker image.

**Comment by ryanho87** [comment]
Basically an environment variable that would allow us to prevent these calculations from running, ie RUN_CALCS=false.  Another way to solve for this would be to check to see if the keys were present before running the calculation.
