### ISSUE TITLE
Missing windchill value causes Home Assistant to complain

### ISSUE THREAD

**Issue by Anto79-ops** [bachya/ecowitt2mqtt#194]
Hi

Super great integration! I have two devices reporting to ecowitt2mqtt. 

I noticed that the windchill value is "none", and could be because it's summer time.

When does the windchill value start reporting?

 i have some of these values reporting to Google Assistant and have these errors in the logs when the value is none. 

```

Logger: homeassistant.components.google_assistant.smart_home
Source: components/google_assistant/trait.py:838
Integration: Google Assistant (documentation, issues)
First occurred: June 28, 2022, 10:24:45 PM (24 occurrences)
Last logged: June 28, 2022, 11:06:20 PM

Unexpected error serializing query for <state sensor.windchill=None; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=windchill @ 2022-06-28T14:18:31.165218-06:00>
Unexpected error serializing query for <state sensor.windchill_2=None; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=windchill @ 2022-06-28T14:17:26.774925-06:00>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/smart_home.py", line 138, in async_devices_query
    devices[devid] = entity.query_serialize()
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py", line 648, in query_serialize
    deep_update(attrs, trt.query_attributes())
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/trait.py", line 838, in query_attributes
    temp = round(temp_util.convert(float(current_temp), unit, TEMP_CELSIUS), 1)
ValueError: could not convert string to float: 'None' 

```

**Comment by bachya** [comment]
> I noticed that the windchill value is "none", and could be because it's summer time.
>
> When does the windchill value start reporting?

You are correct: windchill is on calculable at certain temperature/wind speed combinations. From the [US National Weather Service](https://www.weather.gov/safety/cold-wind-chill-chart):

> Wind Chill Temperature is defined only for temperatures at or below 50°F and wind speeds above 3 mph.

---

> i have some of these values reporting to Google Assistant and have these errors in the logs when the value is none.
>
> ```
> Logger: homeassistant.components.google_assistant.smart_home
> Source: components/google_assistant/trait.py:838
> Integration: Google Assistant (documentation, issues)
> First occurred: June 28, 2022, 10:24:45 PM (24 occurrences)
> Last logged: June 28, 2022, 11:06:20 PM

> Unexpected error serializing query for <state sensor.windchill=None; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=windchill @ 2022-06-28T14:18:31.165218-06:00>
> Unexpected error serializing query for <state sensor.windchill_2=None; state_class=measurement, unit_of_measurement=°C, device_class=temperature, friendly_name=windchill @ 2022-06-28T14:17:26.774925-06:00>
> Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/smart_home.py", line 138, in async_devices_query
    devices[devid] = entity.query_serialize()
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py", line 648, in query_serialize
    deep_update(attrs, trt.query_attributes())
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/trait.py", line 838, in query_attributes
    temp = round(temp_util.convert(float(current_temp), unit, TEMP_CELSIUS), 1)
ValueError: could not convert string to float: 'None' 
```

Ah, okay – it doesn't like the fact that we set a `None` value... Let me think on this a bit. We may need to refrain from publishing windchills without a value altogether.

**Comment by Anto79-ops** [comment]
Thanks and good to know!

I just recently removed another Ecowitt Intergration and the history of this sensor was there...I think the windchill value was actually the temperature value when there is no windchill...if that helps.

**Comment by bachya** [comment]
Okay, I've got an elegant solution (and since this is an HA issue – it doesn't like `None` values for temperature sensors – we fix it at the HASS layer).

If the conditions exist, we display windchill as expected:

![CleanShot 2022-06-29 at 08 31 13@2x](https://user-images.githubusercontent.com/47216/176462573-eb9c3309-c08a-4e76-8f66-f6447688c0b0.png)

If the conditions don't exist, we mark the entity as `unavailable`:

![CleanShot 2022-06-29 at 08 30 09@2x](https://user-images.githubusercontent.com/47216/176462650-99a219c5-f7ed-4a7f-ad8e-c0db2246258d.png)

This is more consistent with how HASS works and will stop the logged issue you're seeing.

Thoughts?

**Comment by Anto79-ops** [comment]
This is very nice how it should be because by definition of the NWS!

**Comment by bachya** [comment]
Great! I'll get that implemented and cut a new version today (I'll post back here when it's done).

**Comment by Anto79-ops** [comment]
thanks! since im running this on a dedicated RPi and installed it by:

`sudo pip install ecowitt2mqtt`

To apply any updates, do I simply just type:

`sudo pip install ecowitt2mqtt --upgrade`

and restart the service?

`sudo service ecowitt2mqtt restart`

**Comment by bachya** [comment]
Correct. 👍🏻

**Comment by bachya** [comment]
Alrighty, implemented in [2022.06.6](https://github.com/bachya/ecowitt2mqtt/releases/tag/2022.06.6) – it's been published to PyPI, so you're free to upgrade!

**Comment by Anto79-ops** [comment]
sweet! Just upgraded and now both my windchill entities (from 2 different devices) are unavailable.

Cheers, Aaron.

**Comment by Anto79-ops** [comment]
I just realized, there is also a heatindex entity. Would this value also become none, unavaiable or number in the colder (winter) months?

**Comment by bachya** [comment]
@Anto79-ops I don't think that's an issue: the National Weather Service doesn't show any caveat on [the heat index page](https://www.weather.gov/ffc/hichart) (like they did with windchill) and `meteocalc` (the library we use for meteorological calculations) doesn't have any sort of exception handling in [the heat index code](https://github.com/malexer/meteocalc/blob/master/meteocalc/heatindex.py) (whereas [the windchill code](https://github.com/malexer/meteocalc/blob/master/meteocalc/windchill.py) does).

**Comment by Anto79-ops** [comment]
Fantastic! cheers
