### ISSUE TITLE
Lightning distance output is incorrect

### ISSUE THREAD

**Issue by Anto79-ops** [bachya/ecowitt2mqtt#197]
Hi

I'm unable to determine how the lightning distance is reported. It seems to report values that are over 40 km, and not consistent with those reported with the Gateway.

Should be 40 km maximum, and for example, here the last strike recorded by the Gateway was 34 km:

![Screenshot_20220629-230557](https://user-images.githubusercontent.com/79593761/176598280-4ab46393-2c4b-4211-987d-c48fdc1b0d77.jpg)

But ecowitt2mqtt is reporting 54.7 km:

![Screenshot_20220629-230543](https://user-images.githubusercontent.com/79593761/176598396-c1f87c1b-e924-4365-9751-6bd675124c04.jpg)

Using it with HA and the following configs

--mqtt-broker=192.168.1.139
--output-unit-system metric
--hass-discovery

**Comment by bachya** [comment]
Please provide a diagnostics dump.

**Comment by bachya** [comment]
Thanks! I see the raw data does, indeed, show 34, so something must be happening in data translation. I'll look into it.

**Comment by bachya** [comment]
Okay, I see what's happening. In #105, I learned that lightning distance always arrives in metric units; in #144, I neglected to include that in the new architecture.

**Comment by Anto79-ops** [comment]
i figured it had something to do with units because it seems to be off similar amounts (20 km)...glad you it!

**Comment by Anto79-ops** [comment]
just updated and now reports as the gateway. thanks for the quick fix! Cheers
