### ISSUE TITLE
Implement "official" Home Assistant OS add-on in a companion repo

### ISSUE THREAD

**Issue by nanosonde** [bachya/ecowitt2mqtt#208]
Currently the unit of measurement for the rain rate is "mm" or "in" which is not a correct unit for a rate.
However, home assistant also supports the correct unit of measurement: mm/hr for example.

It can be found here: https://github.com/home-assistant/core/blob/d7ac4bd65379e11461c7ce0893d3533d8d8b8cbf/homeassistant/const.py#L483
```
# Precipitation units
PRECIPITATION_MILLIMETERS_PER_HOUR = "mm/h"
```

It would be nice of this could be changed.

**Comment by nanosonde** [comment]
Oops. Sorry for the confusion.
I am using this addon to get ecowitt2mqtt working: https://github.com/smarthall/hassio-addons

BTW: would it be an option that you maintain an addon version in your repo?

**Comment by bachya** [comment]
Got it!

Daniel and I originally landed on him owning the add-on because I'm not a HASS OS user. That said, as I've watched it, I don't think add-on maintenance is that big of a lift... and in that case, it probably does make more sense for me to manage it in this repo.

Let me open up and issue over there and get the conversation started.

**Comment by bachya** [comment]
I'm noticing that Daniel hasn't responded to that issue. He may be busy or indisposed. That said, after some research, I think I'm ready to go ahead and build an "official" add-on; you can track progress here: https://github.com/bachya/ecowitt2mqtt-home-assistan-addon

**Comment by Anto79-ops** [comment]
Awesome! would this allow one to install your integration within HA, without an external RPi, for example?

**Comment by bachya** [comment]
@Anto79-ops Depending on your installation method, you can already do that today. That said, if you are a HASS OS user, this will become the official add-on.

**Comment by bachya** [comment]
Quick update – I've been busy with work and other projects, but have been slowly making progress on this: https://github.com/bachya/ecowitt2mqtt-home-assistant-addon/pull/4

Needs more testing/docs/Docker Hub setup, but we're moving!

**Comment by bachya** [comment]
We have a working add-on!

![CleanShot 2022-07-22 at 22 04 03](https://user-images.githubusercontent.com/47216/180589793-c13e459b-8779-4fb4-b407-67e2aa9c994c.png)

![CleanShot 2022-07-22 at 22 04 09](https://user-images.githubusercontent.com/47216/180589796-dcaecf30-61b7-4ddf-bfd6-20ee958caee2.png)

Working on docs + Docker Hub publishing next.

**Comment by Anto79-ops** [comment]
Awesome! Please let us know when we can start using this.

**Comment by VictorvandenHoven** [comment]
> We have a working add-on!
> 
> ![CleanShot 2022-07-22 at 22 04 03](https://user-images.githubusercontent.com/47216/180589793-c13e459b-8779-4fb4-b407-67e2aa9c994c.png)
> 
> ![CleanShot 2022-07-22 at 22 04 09](https://user-images.githubusercontent.com/47216/180589796-dcaecf30-61b7-4ddf-bfd6-20ee958caee2.png)
> 
> Working on docs + Docker Hub publishing next.

Thanks very much for this!

Can't wait to try it out!
