### ISSUE TITLE
Allow overriding values for unavailable Home Assistant entities

### ISSUE THREAD

**Issue by alexdelprete** [bachya/ecowitt2mqtt#220]
**Is your feature request related to a problem? Please describe.**
not a problem, but I noticed the windchill sensor in HA is almost always unavailable. Checking the debug log I found the reason:

```
"Wind Chill Temperature is only defined for temperatures at or below 50 F and wind speeds above 3 mph. (temperature: 77.72, wind speed: 0.0)"
```

**Describe the solution you'd like**
An option to have the sensor always enabled, like in ecowitt UI:

![image](https://user-images.githubusercontent.com/7027842/180093503-be21bb36-4eb4-4b03-87da-c7f43a2b8da0.png)

**Additional context**
Personally I don't like sensors, even calculated ones, that are dynamically available/unavailable. Initially I thought it was a bug, but it was by design. :)

Maybe this request should be generalized to all sensors not just WindChill, I noticed other sensors are unavailable dynamically.

Thanks.

**Comment by bachya** [comment]
I'm not understanding the request. Wind chill is only defined for certain temperature/wind speed combinations; if those don't exist, the sensor is marked as `unavailable` because that most accurately reflects its state.

**Comment by alexdelprete** [comment]
Right now the ecowitt console reports the windchill (25.3°) while the integration has the sensor unavailable.

What I'm asking is a config option to force these kind of sensors to be always available. For sensors related to the sun, during the night, a value of 0 or n/a is preferrable respect to have them unavailable.

**Comment by alexdelprete** [comment]
So when there's no wind, does the wind sensor go unavailable?

Another question: what's the best way to disable all these calculated sensors not provided by the station? If I disable them on the MQTT integration, will it create issues at the next cycle?

**Comment by bachya** [comment]
> So when there's no wind, does the wind sensor go unavailable?

No – in that case, a value of 0 has understood meaning: there isn't any wind for this time period. The underlying conditions for wind to exist are still present.

> Another question: what's the best way to disable all these calculated sensors not provided by the station? If I disable them on the MQTT integration, will it create issues at the next cycle?

In Home Assistantat, you can disable individual entities by opening their details window and looking under "Advanced settings." Disabling them in Home Assistantat won't harm ecowitt2mqtt.
