### ISSUE TITLE
Add wind force based on Beaufort wind force scale

### ISSUE THREAD

**Issue by MGdRomph** [bachya/ecowitt2mqtt#239]
A nice addition could be adding the wind force based on Beaufort wind force scale, https://en.wikipedia.org/wiki/Beaufort_scale .

Some items, for example a rotary dryer or sunshades, can be used till a certain wind force. For many of these items this is based on the Beaufort scale. In the Netherlands wind speeds in weather reports are given using this same Beaufort scale.

**Comment by bachya** [comment]
Great idea!

**Comment by bachya** [comment]
What do you think would be the best value: the Beaufort number or the Description (e.g., `Calm`)? In the documentation you've read, what's the most common representation?

**Comment by MGdRomph** [comment]
The Beaufort number is most commonly being used.
