### ISSUE TITLE
Stopped publishing messages with mile long log

### ISSUE THREAD

**Issue by mike240se** [bachya/ecowitt2mqtt#24]
**ecowitt2mqtt version**
Current docker dev

**Describe the bug**
i noticed that my soil sensors were showing old numbers in HA, so went to investigate and mqtt explorer says the last update was 11/6/20.   I did a docker-compose logs and it literally went for 10 minutes+.   I'm not sure what to make of that in itself but it seemed odd such a huge log backlog was available.  (where is this log stored? memory? there is no huge log file in the ccontainer i could find)

the last tens of thousands of log messages were:

ecowitt2mqtt    | ERROR:ecowitt2mqtt:Error while publishing data to MQTT: [code:4] Could not publish message
ecowitt2mqtt    | ERROR:ecowitt2mqtt:Error while publishing data to MQTT: [code:4] Could not publish message
ecowitt2mqtt    | ERROR:ecowitt2mqtt:Error while publishing data to MQTT: [code:4] Could not publish message
ecowitt2mqtt    | ERROR:ecowitt2mqtt:Error while publishing data to MQTT: [code:4] Could not publish message

my mqtt broker is running fine this whole time with all other mqtt integrations working fine.

the supervisor log last message was from 10/31/20.

i left the container still running for now incase there is any info you want me to grab from it before i restart it.

**Additional context**
I guess this would be a feature request, but could we add a timestamp status so home assistant can mark them as unavailable if they arent updated for a long period of time?  I know this is how other mqtt integrations work with home assistant.

**Comment by mike240se** [comment]
It crashes about every 3-5 days on me.  I stop the docker, restart it and then it works again for 3-5 days, and then i have to restart it again.   I tried looking into what Code 4 might mean, I think it means username/pw is incorrect for the mqtt broker but that must be wrong because its not incorrect and it works for days with the same username and pw and then works after the restart so I might be wrong what cod 4 is...

**Comment by bachya** [comment]
Thanks for this info, @mike240se. I'm digging in.

**Comment by hhinma** [comment]
I've seen it following a system restart this past weekend.  restarting the container solves the problem.  I cannot confirm that it has NOT occurred at other times since this is a relatively new setup.  I will pay more attention to it to see if I observe the behavior in conditions other than system restart.

**Comment by mike240se** [comment]
so far working great after the update.  thanks much @bachya !!!!

Regarding the logging though, its MUCH improved.  Looks so much better and cleaner when running docker-compose logs.  However, it still seems like the log history is unlimited, its much less data than before so probably not an issue but i am curious where is this giant unlimited backlog stored?  Is it stored in docker, the container or in memory somewhere?   My only concern is what happens after its been running for 6 months if the back log is truly unlimited as it appears.  thanks.

**Comment by bachya** [comment]
@mike240se By default, Docker logs are stored in an OverlayFS on disk. This is handled by the Docker daemon itself and can be controlled globally or per-image: https://medium.com/@Quigley_Ja/rotating-docker-logs-keeping-your-overlay-folder-small-40cfa2155412
