### ISSUE TITLE
Doesn't work in Metric

### ISSUE THREAD

**Issue by megusd** [bachya/ecowitt2mqtt#241]
**Describe the bug**
When change ECOWITT2MQTT_INPUT_UNIT_SYSTEM variable to **metric** no data coming through

**To Reproduce**
Change to Metric

**Diagnostics**
2 Runs with verbose logging, Metric and Imperial

**Additional context**
Last run in metric
[ecowitt2mqtt-3.csv](https://github.com/bachya/ecowitt2mqtt/files/9233876/ecowitt2mqtt-3.csv)
un in metric

Last run in imperial
[ecowitt2mqtt-4.csv](https://github.com/bachya/ecowitt2mqtt/files/9233897/ecowitt2mqtt-4.csv)

**Comment by bachya** [comment]
You appear to be using an old version. Please upgrade to 2022.07.7.

**Comment by megusd** [comment]
Yes, running 2022.07.7 container on Sinology(DSM7.1) docker.

The combination of INPUT:imperial and OUTPUT:Metric fixed the issue. 
Sorry, I missed it in documentation
