### ISSUE TITLE
Bug in calculate_simmer_zone

### ISSUE THREAD

**Issue by alfredopironti** [bachya/ecowitt2mqtt#249]
I'm running ecowitt2mqtt as an Home Assistant addon, and it crashes with the following debug information:

```
2022-08-14 18:20:46,675 | ecowitt2mqtt | DEBUG | Received data from the Ecowitt device: {'PASSKEY': '<redacted>', 'stationtype': 'GW2000A_V2.1.8', 'runtime': '35171', 'dateutc': '2022-08-14 16:20:46', 'tempinf': '81.68', 'humidityin': '33', 'baromrelin': '27.605', 'baromabsin': '27.605', 'tempf': '86.90', 'humidity': '19', 'winddir': '162', 'windspeedmph': '2.68', 'windgustmph': '13.65', 'maxdailygust': '19.68', 'solarradiation': '348.54', 'uv': '3', 'rrain_piezo': '0.000', 'erain_piezo': '0.016', 'hrain_piezo': '0.012', 'drain_piezo': '0.000', 'wrain_piezo': '0.000', 'mrain_piezo': '0.000', 'yrain_piezo': '0.000', 'ws90cap_volt': '5.3', 'ws90_ver': '119', 'wh90batt': '2.28', 'freq': '868M', 'model': 'GW2000A'}
> INFO:     10.0.100.40:63384 - "POST /data/report HTTP/1.1" 204 No Content
> 2022-08-14 18:20:46,676 | ecowitt2mqtt | DEBUG | Publishing payload: {'PASSKEY': '<redacted>', 'stationtype': 'GW2000A_V2.1.8', 'runtime': '35171', 'dateutc': '2022-08-14 16:20:46', 'tempinf': '81.68', 'humidityin': '33', 'baromrelin': '27.605', 'baromabsin': '27.605', 'tempf': '86.90', 'humidity': '19', 'winddir': '162', 'windspeedmph': '2.68', 'windgustmph': '13.65', 'maxdailygust': '19.68', 'solarradiation': '348.54', 'uv': '3', 'rrain_piezo': '0.000', 'erain_piezo': '0.016', 'hrain_piezo': '0.012', 'drain_piezo': '0.000', 'wrain_piezo': '0.000', 'mrain_piezo': '0.000', 'yrain_piezo': '0.000', 'ws90cap_volt': '5.3', 'ws90_ver': '119', 'wh90batt': '2.28', 'freq': '868M', 'model': 'GW2000A'}

[...]

2022-08-14 18:20:46,678 | ecowitt2mqtt | DEBUG | Sending DISCONNECT
> 2022-08-14 18:20:46,679 | ecowitt2mqtt | ERROR | not enough values to unpack (expected 1, got 0)
> 2022-08-14 18:20:46,680 | ecowitt2mqtt | DEBUG |   File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/helpers/logging.py", line 47, in wrapper
>     return func(*args, **kwargs)
>   File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/cli.py", line 229, in main
>     loop.run_until_complete(ecowitt.async_start())
>   File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
>   File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/core.py", line 46, in async_start
>     await self._runtime.async_start()
>   File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/runtime.py", line 160, in async_start
>     await asyncio.gather(*self._runtime_tasks)
>   File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/runtime.py", line 94, in _async_create_mqtt_loop
>     await self._publisher.async_publish(
>   File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/helpers/publisher/hass.py", line 481, in async_publish
>     processed_data = ProcessedData(self.ecowitt, data)
>   File "<string>", line 6, in __init__
>   File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/data.py", line 298, in __post_init__
>     self.output[payload_key] = calculator(
>   File "/usr/lib/python3.9/site-packages/ecowitt2mqtt/helpers/calculator/meteo.py", line 917, in calculate_simmer_zone
>     [rating] = [
```

The debug info was quite handy pinpointing me to the exact line in `calculate_simmer_zone` that is failing, but I couldn't understand why any better.

In this report, I'm including the info received by the ecowitt gateway, in case it helps with debugging. For completeness (it can be inferred from the log), I'm using WittBoy with GW2000A and the WS90 all-in-one weather station.

Please let me know if I can support with any further information or testing on my side. Thanks!

**Comment by bachya** [comment]
Thanks! I just ran your raw payload (appreciate you providing that) in a fresh instance of 2022.08.1, and it published correctly with no error. Can you confirm that you're using 2022.08.1?

**Comment by bachya** [comment]
(Referencing https://github.com/bachya/ecowitt2mqtt/issues/221 in case there's a broader problem. That issue included the same unhandled exception with simmer zone calculation, but [it was determined the user had configured incorrect unit systems](https://github.com/bachya/ecowitt2mqtt/issues/221#issuecomment-1199941209).)

**Comment by alfredopironti** [comment]
Gotcha, and changing ecowitt2mqtt "input unit system" config from "metric" to "imperial" did the trick. On the GW2000A interface I set the units to metric, so I assumed the gateway would push info in metric, which is not the case.

Problem seems solved, thanks! I'd wonder if there's a way to catch this error pattern, but guessing the units from the raw data is probably a lost cause.

Thanks for all the help, and great job!

**Comment by bachya** [comment]
@alfredopironti Great point. I have yet to see a gateway that doesn't transmit its units in imperial, so maybe if somebody sets their input units to metric, I can log a warning for them... Will think on it!

**Comment by alfredopironti** [comment]
Makes sense! If a user sets the input units as metrics, you could raise a warning in the log. If the warning could contain, for example, the latest reported (raw) temperature, it could ease spotting the issue. After your comment, I could pinpoint the issue myself when I looked back at my own log, and had `'tempinf': '81.68'`: I wouldn't be here if that was Celsuis :-)
