### ISSUE TITLE
Docker image for arm/v7

### ISSUE THREAD

**Issue by freeball155** [bachya/ecowitt2mqtt#289]
Hello.

Thanks for your work.

I am using ecowitt2mqtt as docker image (https://hub.docker.com/r/bachya/ecowitt2mqtt) for raspberry pi 4 (arm/v7). However, versions starting from 2022.08.03 do not have the armv7 tag. I tried to build the image myself through the Dockerfile, but the docker builder ended with an error: This package requires Rust >=1.48.0. It turned out that cryptography requires cargo package - https://github.com/pyca/cryptography/blob/main/docs/installation.rst#alpine After I added the cargo to the Dockerfile, everything worked out.

So I have two questions:
1) Is it possible to fix the Dockerfile?
2) You no longer have the ability to build images for armv7? If you don't have access to raspberry pi 4, I can build the images myself and send them to you, so you can put them on docker hub.

**Comment by bachya** [comment]
Some time ago, I removed `armv7` support becuase of `cryptography`'s transition to Rust (which you ran into on your system) + a bug re: QEMU publishing 32-bit images on a 64-bit architecture (relevant issues: https://github.com/pyca/cryptography/issues/6347, https://github.com/rust-lang/cargo/issues/8719, https://bugs.launchpad.net/qemu/+bug/1805913) - this makes it to that our GitHub Actions can't publish the `armv7` image as-is.

I now see I was mistaken to assume that every Pi user was on a 64-bit architecture. 😆 

In digging around, I see that the `healthchecks` project figure out a way to do this: https://github.com/healthchecks/healthchecks/issues/568#issuecomment-942047344. Let me see if this can work for us.

**Comment by bachya** [comment]
@freeball155 This was added in #292. You can use the latest right away via the [`pr-292`](https://hub.docker.com/layers/bachya/ecowitt2mqtt/pr-292/images/sha256-c31a21bd249db1878791427569fd802968d4ca823fe3f41bc025f8d64655267d?context=explore) tag, or you can wait for [the latest `dev` tag to build](https://github.com/bachya/ecowitt2mqtt/actions/runs/3086783973/jobs/4991490401). Going forward, tagged versions will have an `armv7` image, too.
