### ISSUE TITLE
`ECOWITT2MQTT_HASS_DISCOVERY` variable with `False` value will still use MQTT Discovery

### ISSUE THREAD

**Issue by bachya** [bachya/ecowitt2mqtt#299]
Revealed by https://github.com/bachya/ecowitt2mqtt/issues/297. Our schema isn't translating things correctly.

**Comment by barcar** [comment]
@bachya it looks like the DockerHub publish is failing. Would you be able to take a look please?

**Comment by bachya** [comment]
@barcar I saw that. I'm on the road and busy for most of today, but will take a look as soon as I'm able.

**Comment by bachya** [comment]
@barcar FYI, still diagnosing here and there while on the road. Working via https://github.com/bachya/ecowitt2mqtt/pull/301, so keep an eye on that one getting merged.

**Comment by bachya** [comment]
@barcar We're back in business. Keep an eye on [the 2022.10.0 image](https://github.com/bachya/ecowitt2mqtt/actions/runs/3166961324).
