### ISSUE TITLE
Feature Request: Customize unit settings per entity

### ISSUE THREAD

**Issue by ketilmo** [bachya/ecowitt2mqtt#308]
**Is your feature request related to a problem? Please describe.**
Thanks for creating an amazing weather solution. It works great. An extension I would enjoy is being able to choose unit settings per entity, in the same way that the Ecowitt UI allows for. 

**Describe the solution you'd like**
Be able to choose the unit types for
- Temperature (°C, °F) 
- Pressure (hPa, inHgm, mmHg)
- Wind (m/s, km/h, mph, knots)
- Rain (mm, in)
- Irradiance (Klux, W/㎡, Kfc)

**Additional context**
See screenshot from Ecowitt GW1100 settings page.
![Settings](https://user-images.githubusercontent.com/8332946/194753518-56abbf67-5668-47c3-a9d8-e316de64bb4b.png)

**Comment by bachya** [comment]
To confirm: you're wanting to choose the units per entity _category_ (temperature, etc.), not per each individual entity?

**Comment by ketilmo** [comment]
Hi @bachya,

Thanks for your quick reply. Yes, that's correct. Category would be sufficient.

**Comment by bachya** [comment]
Got it; thanks!

**Comment by bachya** [comment]
Putting down some thoughts.

Underneath the hood, this isn't challenging. We can abstract unit conversion logic into a set of `UnitConverter` objects that take a "normalized unit" (e.g., perhaps we use "length in meters" for distance) and then store conversions to various other units.

The more challenging part is configuration – what is the least "breaking," most user-friendly way to implement this? More specifically:

1. Can the existing configuration options – `--input-unit-system` and `--output-unit-system` – still provide value? Perhaps as a global conversion that can then be refined per unit category?
2. How should the user provide unit configurations for an entity category? Something like `--temperature-unit=c`?

Will start working on the backend while I chew on this.

**Comment by bachya** [comment]
@ketilmo Thanks for your patience! I've been hard at work and I'm now starting to implement the final user-facing portion of this: #338 

In particular, take a look at [what I'm proposing in the docs](https://github.com/bachya/ecowitt2mqtt/blob/4715da922c307dcf0e725638997d72bdb0856b8f/README.md#unit-systems) and see if it makes sense to you. Thanks!

**Comment by ketilmo** [comment]
Wow @bachya,

That was fast! Thanks a lot for your efforts, they are much appreciated. I checked the docs, and this looks like a great solution on how to handle the settings from a user perspective.

**Comment by bachya** [comment]
Alright, with #346, this is completed for all unit categories. I have a few other PRs to add, but I will cut a release later today (and post back here when I do).

**Comment by bachya** [comment]
@ketilmo 2022.10.1 release with this functionality. Enjoy!

**Comment by ketilmo** [comment]
Awesome, @bachyae! I can't wait to check it out! I'm running it as an add-on. Is there a way to change the settings through the UI?

**Comment by bachya** [comment]
I haven't exposed any of this to the Home Assistant add-on because I didn't want to duplicate functionality that HASS already has:

![CleanShot 2022-10-17 at 09 15 02](https://user-images.githubusercontent.com/47216/196215939-2e199156-2472-40f9-914d-472f755a8fc4.png)

**Comment by bachya** [comment]
After investigating a bit, perhaps that thinking is erroneous – HASS only appears to allow you to alter _some_ units (like temperature), but not others. Has that been your experience, too, @ketilmo?

**Comment by ketilmo** [comment]
Nice! I wasn't aware of the possibility of changing the sensor type per entity. But you're right, it doesn't seem to work wind, rain and irradiance.

**Comment by bachya** [comment]
Thanks for checking. I'll expose my options to the add-on and will report back.

**Comment by bachya** [comment]
Give me your thoughts: would it be worth exposing all of our options in the add-on, or only those options that HASS doesn't already cover (i.e., everything _except_ temperature and pressure)?

The former is probably the easiest/clearest to do, but appreciate your opinion.

**Comment by ketilmo** [comment]
+1 for the second option. Hopefully, Home Assistant will eventually implement the UI unit setting for more types. So this might be a temporary workaround.

**Comment by ketilmo** [comment]
I have raised a feature request for this over at the Home Assistant forums: https://community.home-assistant.io/t/customisable-units-for-more-sensor-types/476474?u=ketil

**Comment by bachya** [comment]
@ketilmo Okay, version 2022.10.1 of the add-in is [building](https://github.com/bachya/home-assistant-addons/actions/runs/3269408962), and once it's complete (and you upgrade), you'll be able to configure units other than temperature and pressure:

![CleanShot 2022-10-17 at 17 09 11](https://user-images.githubusercontent.com/47216/196302418-4701e772-fdf3-4866-b9f4-34295be8d02b.png)

To configure these options in the add-on, you'll need to toggle "Show unused optional configuration options" first.

P.S., that strange UI – where a config option with two possible values shows radio buttons, and >2 shows a dropdown – Is in Home Assistant OS and not something I can change, unfortunately.

**Comment by ketilmo** [comment]
This works like a charm, @bachya! Thanks for your efforts and making this happen! 👏🏻
