### ISSUE TITLE
Yaml Location

### ISSUE THREAD

**Issue by robyevolution** [bachya/ecowitt2mqtt#318]
Hi i can't find the yaml file to edit, i installed ecowitt2mqtt on raspberry, where can i find it?

**Comment by bachya** [comment]
Which YAML file are you referring to?

**Comment by robyevolution** [comment]
the yaml file where I can enter the configuration data, mqtt, ip, etc. etc.

**Comment by bachya** [comment]
That file is not automatically created (since we assume that most users will prefer command line options or environment variables). You will need to create it yourself (an example is in the documentation) and pass it to `ecowitt2mqtt`.
