### ISSUE TITLE
Converting from imperial to metric gives to much decimals

### ISSUE THREAD

**Issue by aholzel** [bachya/ecowitt2mqtt#354]
**Describe the bug**
Since one of the last versions the calculations done to go from imperial input to metric output aren't rounded. so now the values like "20.38888888888889 °C" for the current temp. and "0.20320000000000002 mm" rain fall today, and "36.6930432 km/h" for wind speed.

**To Reproduce**
1. make sure the input is in imperial
2. make sure the output is metric
3. look at the values send to mqtt

**Diagnostics**
N/A

**Additional context**
my suggestion is to either give the user the option to round these values to a given number or round them all to 2 decimals.

**Comment by bachya** [comment]
See https://github.com/bachya/ecowitt2mqtt/pull/347. In short, use the `--precision INTEGER` config option.

**Comment by aholzel** [comment]
my sincere apologies for not reading the documentation correct! I think it has something to do with the ecowitt2mqtt prefix of all the options, that was/is confusing me a bit.

**Comment by bachya** [comment]
No need to apologize! All good.

> I think it has something to do with the ecowitt2mqtt prefix of all the options, that was/is confusing me a bit.

Reminder that only environment variables are prefixed with `ECOWITT2MQTT_` (so they don't collide with others).
