### ISSUE TITLE
2022.10.3: Data Precision setting not working

### ISSUE THREAD

**Issue by alexdelprete** [bachya/ecowitt2mqtt#362]
**Describe the bug**
The setting introduced in #347 doesn't seem to be applied.
Regarding this, I remember reading in the past that HA has introduced a default precision based on device_class of the sensor, shouldn't that prevent these kind of issues?

**To Reproduce**
```yaml
ECOWITT2MQTT_PORT: 8080
ECOWITT2MQTT_INPUT_UNIT_SYSTEM: imperial
ECOWITT2MQTT_OUTPUT_UNIT_SYSTEM: metric
ECOWITT2MQTT_DISABLE_CALCULATED_DATA: true
ECOWITT2MQTT_VERBOSE: false
ECOWITT2MQTT_MQTT_BROKER: mqtt.axel.dom
ECOWITT2MQTT_MQTT_PORT: 1883
ECOWITT2MQTT_MQTT_RETAIN: false
ECOWITT2MQTT_MQTT_TLS: false
ECOWITT2MQTT_MQTT_TOPIC: ecowitt2mqtt/GW2000A
ECOWITT2MQTT_ENDPOINT: /data/report
ECOWITT2MQTT_HASS_DISCOVERY: true
ECOWITT2MQTT_HASS_DISCOVERY_PREFIX: homeassistant
ECOWITT2MQTT_HASS_ENTITY_ID_PREFIX: ecowitt
ECOWITT2MQTT_PRECISION: 2
```

**Expected behavior**
Respect of the ECOWITT2MQTT_PRECISION value.

**Screenshots**
![image](https://user-images.githubusercontent.com/7027842/199000592-6d4574cd-f4ed-4802-a6be-d1addc18f87f.png)
![image](https://user-images.githubusercontent.com/7027842/199000994-f0e921cf-9a1f-481f-a3b7-ddf2d2596f45.png)

**Comment by Anto79-ops** [comment]
interesting, is working on my platform RPi 2022.10.3. Maybe a addon issue only.

**Comment by alexdelprete** [comment]
Yes I am.

@bachya isn't ENV_PRECISION missing here? (__main__.py):

```python
def get_env_vars() -> dict[str, str]:
    """Get environment variables.
    Returns:
        A dictionary of environment variables to config options.
    """
    env_vars = {}

    for env_var in (
        ENV_BATTERY_OVERRIDES,
        ENV_CONFIG,
        ENV_DEFAULT_BATTERY_STRATEGY,
        ENV_DIAGNOSTICS,
        ENV_DISABLE_CALCULATED_DATA,
        ENV_ENDPOINT,
        ENV_HASS_DISCOVERY,
        ENV_HASS_DISCOVERY_PREFIX,
        ENV_HASS_ENTITY_ID_PREFIX,
        ENV_INPUT_UNIT_SYSTEM,
        ENV_MQTT_BROKER,
        ENV_MQTT_PASSWORD,
        ENV_MQTT_PORT,
        ENV_MQTT_RETAIN,
        ENV_MQTT_TLS,
        ENV_MQTT_TOPIC,
        ENV_MQTT_USERNAME,
        ENV_OUTPUT_UNIT_SYSTEM,
        ENV_OUTPUT_UNIT_TEMPERATURE,
        ENV_PORT,
        ENV_RAW_DATA,
        ENV_VERBOSE,
        LEGACY_ENV_ENDPOINT,
        LEGACY_ENV_HASS_DISCOVERY,
        LEGACY_ENV_HASS_DISCOVERY_PREFIX,
        LEGACY_ENV_HASS_ENTITY_ID_PREFIX,
        LEGACY_ENV_INPUT_UNIT_SYSTEM,
        LEGACY_ENV_LOG_LEVEL,
        LEGACY_ENV_MQTT_BROKER,
        LEGACY_ENV_MQTT_PASSWORD,
        LEGACY_ENV_MQTT_PORT,
        LEGACY_ENV_MQTT_TOPIC,
        LEGACY_ENV_MQTT_USERNAME,
        LEGACY_ENV_OUTPUT_UNIT_SYSTEM,
        LEGACY_ENV_PORT,
        LEGACY_ENV_RAW_DATA,
    ):
```

**Comment by alexdelprete** [comment]
> interesting, is working on my platform RPi 2022.10.3. Maybe a addon issue only.

you're using cli option, I'm using env variable. that's where I suspect the problem is...mapping variables to config options.

**Comment by alexdelprete** [comment]
> a, mannaggia env :)

ehhhhh...il diavolo è nei piccoli dettagli...;)

**Comment by bachya** [comment]
> Yes I am.
> 
> 
> 
> @bachya isn't `ENV_PRECISION` missing here? (__main__.py):
> 
> 
> 
> ```python
> 
> def get_env_vars() -> dict[str, str]:
> 
>     """Get environment variables.
> 
>     Returns:
> 
>         A dictionary of environment variables to config options.
> 
>     """
> 
>     env_vars = {}
> 
> 
> 
>     for env_var in (
> 
>         ENV_BATTERY_OVERRIDES,
> 
>         ENV_CONFIG,
> 
>         ENV_DEFAULT_BATTERY_STRATEGY,
> 
>         ENV_DIAGNOSTICS,
> 
>         ENV_DISABLE_CALCULATED_DATA,
> 
>         ENV_ENDPOINT,
> 
>         ENV_HASS_DISCOVERY,
> 
>         ENV_HASS_DISCOVERY_PREFIX,
> 
>         ENV_HASS_ENTITY_ID_PREFIX,
> 
>         ENV_INPUT_UNIT_SYSTEM,
> 
>         ENV_MQTT_BROKER,
> 
>         ENV_MQTT_PASSWORD,
> 
>         ENV_MQTT_PORT,
> 
>         ENV_MQTT_RETAIN,
> 
>         ENV_MQTT_TLS,
> 
>         ENV_MQTT_TOPIC,
> 
>         ENV_MQTT_USERNAME,
> 
>         ENV_OUTPUT_UNIT_SYSTEM,
> 
>         ENV_OUTPUT_UNIT_TEMPERATURE,
> 
>         ENV_PORT,
> 
>         ENV_RAW_DATA,
> 
>         ENV_VERBOSE,
> 
>         LEGACY_ENV_ENDPOINT,
> 
>         LEGACY_ENV_HASS_DISCOVERY,
> 
>         LEGACY_ENV_HASS_DISCOVERY_PREFIX,
> 
>         LEGACY_ENV_HASS_ENTITY_ID_PREFIX,
> 
>         LEGACY_ENV_INPUT_UNIT_SYSTEM,
> 
>         LEGACY_ENV_LOG_LEVEL,
> 
>         LEGACY_ENV_MQTT_BROKER,
> 
>         LEGACY_ENV_MQTT_PASSWORD,
> 
>         LEGACY_ENV_MQTT_PORT,
> 
>         LEGACY_ENV_MQTT_TOPIC,
> 
>         LEGACY_ENV_MQTT_USERNAME,
> 
>         LEGACY_ENV_OUTPUT_UNIT_SYSTEM,
> 
>         LEGACY_ENV_PORT,
> 
>         LEGACY_ENV_RAW_DATA,
> 
>     ):
> 
> ```

Yep, that's it. 🤦 I'll get a fix (and write a test to prevent that from hindering us in the future).

**Comment by alexdelprete** [comment]
> Yep, that's it. 🤦 I'll get a fix (and write a test to prevent that from hindering us in the future).

No worries: sorry for not letting you know before, can you believe it's the first time all those decimals appeared in the UI? I saw at mose 3-4 digits in the past. When I upgraded to 10.3 I immediately noticed.

**Comment by alexdelprete** [comment]
Aaron: doesn't HA have a default precision based on device_class of the sensor? I remember reading something like that in one of the blog posts of new HA versions, but can't find it...

**Comment by bachya** [comment]
@alexdelprete I think this is where it's done: https://github.com/home-assistant/core/blob/94e2646c875a539f2c48d40eacf24f93f2e69026/homeassistant/components/sensor/__init__.py#L717-L741

**Comment by alexdelprete** [comment]
> I think this is where it's done:

that adapts the precision when scaling to larger units, makes sense. but I remember something about "default precision" for each device_class. Maybe I'm confusing with a FR I'd like for HA. :)

Thanks for the quick fix.

**Comment by bachya** [comment]
Going to keep this open until I create and verify the PR.
