### ISSUE TITLE
"unit_of_measurement" incorrect (compared to unit system)

### ISSUE THREAD

**Issue by MarkThielen** [bachya/ecowitt2mqtt#38]
For some sensors the "unit_of_measurements" are missing which leads to Lovelace Graphing challenges when trying to combine with other sensors of the same "unit". **_This might be connected with the "metric" vs. "imperial" settings_**. For metric counters `temp` and `tempin` adding  the following entries to `hass.py` seem to make it work

```
from ecowitt2mqtt.const import (
...
    DATA_POINT_TEMP,
    DATA_POINT_TEMPIN,
...
)


DATA_POINTS = {
...
    DATA_POINT_TEMP: ("mdi:thermometer", "°C"),
    DATA_POINT_TEMPIN: ("mdi:thermometer", "°C"),
...
}
```

**Comment by MarkThielen** [comment]
Checking the MQTT Broker the following sensors miss units

- temp
- tempin
- baromabs
- baromrel
- dailyrain
- hourlyrain
- monthlyrain
- rainrate
- totalrain
- weeklyrain
- windspeed
- windgust

**Comment by bachya** [comment]
Please paste some examples. When I look at the config topic for the `temp` sensor (`homeassistant/sensor/ID/temp/config`), I see a unit:

```json
{
  "availability_topic": "homeassistant/sensor/ID/temp/availability",
  "icon": "mdi:thermometer",
  "name": "temp",
  "qos": 1,
  "state_topic": "homeassistant/sensor/ID/temp/state",
  "unique_id": "ID_temp",
  "unit_of_measurement": "°F"
}
```

Also, please share the version you are using.

**Comment by MarkThielen** [comment]
Update to 1.0.4 and now Units are present but "metric" units are not working anymore. I do start with the following cmd line

```
/usr/local/bin/ecowitt2mqtt --mqtt-broker=homeassistant.fritz.box --mqtt-username=tasmota --mqtt-password=xxx --hass-discovery --unit-system metric
```

This is what is present in MQTT broker for example in the temperature sensor it uses Fahrenheit and not Celcius.


```
{"availability_topic": "homeassistant/sensor/641BC45267D8313205E7DC98CA552E6C/temp/availability", "icon": "mdi:thermometer", "name": "temp", "qos": 1, "state_topic": "homeassistant/sensor/641BC45267D8313205E7DC98CA552E6C/temp/state", "unique_id": "641BC45267D8313205E7DC98CA552E6C_temp", "unit_of_measurement": "\u00b0F"}
```

**Comment by bachya** [comment]
Ah, okay: the correct metric temperature is being calculated, but the unit isn't coming through in HASS Discovery. I'll look into it.

**Comment by MarkThielen** [comment]
Yes that might be the case. 
There is another thing in Home Assistant that I found :  Lovelace  might already do the calculation. Have a look at the screenshot below. You can see that when I updated the version the value suddenly dropped to a -14.x value but the value passed in the mqtt broker was still  +6.x but with "°F" as Unit and the graph itself is in "C°" ... interesting ;)

![image](https://user-images.githubusercontent.com/6243768/102235812-04985800-3ef3-11eb-8c15-79efb94fb3a2.png)

**Comment by bachya** [comment]
@MarkThielen FYI, this has been fixed in 1.0.5. The PyPI version is live, but the Docker image is still building, FYI.

**Comment by MarkThielen** [comment]
Thanks @bachya I updated and it works. I checked the units in the MQTT broker and found the following with "null" as unit

- windgust
- windspeed
- wh65batt

**Comment by bachya** [comment]
@MarkThielen Thanks! I'll get `windgust` and `windspeed`. `wh65batt` is `0` for me; what should the unit be?

**Comment by MarkThielen** [comment]
> @MarkThielen Thanks! I'll get `windgust` and `windspeed` added shortly.
> 
> `wh65batt` is `0` for me and I'm not sure what that unit should be. Let's move the battery-related discussion to #18

According to this Forum  https://www.wxforum.net/index.php?topic=38922.0 It seems like that 0=Battery OK and 1=Battery Low so we could say there is no unit.
