### ISSUE TITLE
minor - units missing on humidex sensor

### ISSUE THREAD

**Issue by Anto79-ops** [bachya/ecowitt2mqtt#419]
Hi, just wanted to report something minor, I noticed the humidex value is missing the temperature units

![image](https://user-images.githubusercontent.com/79593761/209510987-4d9406a8-bc89-474b-88fa-01661bfc7a7a.png)

running E2M on RPi4 with HASS discovery on.

Happy Holidays!

**Comment by bachya** [comment]
Hi there! Humidex as actually an index, so it doesn't have a definite unit of measurement. More info: https://en.wikipedia.org/wiki/Humidex

Happy holidays!

**Comment by Anto79-ops** [comment]
Interesting! I learned something new everyday.

Cheers
