### ISSUE TITLE
Wrong Device Class for SolarRadiation sensor

### ISSUE THREAD

**Issue by alexdelprete** [bachya/ecowitt2mqtt#427]
Hi Aaron,

This is the device class of SolarRadiation sensor:

![image](https://user-images.githubusercontent.com/7027842/211306559-d9666a28-5751-4f0f-a625-13ce76802c1e.png)

I think it should be IRRADIANCE vs ILLUMINANCE, as per HA docs:

![image](https://user-images.githubusercontent.com/7027842/211306799-7eb85030-70a2-4a00-ba78-7b29d5ae8e5f.png)

**Comment by bachya** [comment]
Great catch, @alexdelprete!
