### ISSUE TITLE
mqtt client disconnected every 120s

### ISSUE THREAD

**Issue by pulcov** [bachya/ecowitt2mqtt#429]
**Describe the bug**
Hi and thank you for your work.
I use ecowitt2mqtt to publish ecowitt gw1100 gateway to mosquitto mqtt server, and all data are used in home assistant.
Every 120s, status becomes offline and all home assistant values are set to undefined.

At same time, no error in ecowitt2mqtt logs but a timeout message is present in mosquitto logs :
`Client 7eNrAgfZ1UqcEud4S0w31x has exceeded timeout, disconnecting.`

I try some config in mosquitto and ecowitt2mqtt without success. Your help to solve my issue would be appreciated.
Thank you

**Screenshots**
![image](https://user-images.githubusercontent.com/16894464/211438877-2434602d-d3cb-44aa-8519-c21fdf6e6cca.png)

**Additional context**
Ecowitt version : GW1100A_V2.0.4
Mosquitto version : docker eclipse-mosquitto 2.0.15
ecowitt2mqtt version : docker bachya/ecowitt2mqtt 2022.12.0
ecowitt gw1100 config:

> protocol: ecowitt
> upload interval: 15s

mosquitto config :

> per_listener_settings false
> listener 1883
> allow_anonymous true
> persistence true
> persistence_location /mosquitto/data
> autosave_interval 600
> include_dir /mosquitto/configinc

ecowitt2mqtt config:

> hass_discovery: true
> mqtt_broker: mosquitto
> mqtt_retain: true
> output_unit_system: metric
> output_unit_speed: km/h

**Comment by bachya** [comment]
How frequently are you publishing data to ecowitt2mqtt?

**Comment by pulcov** [comment]
Ecowitt gateway push data to ecowitt2mqtt every 15s

**Comment by bachya** [comment]
Ah, I see you included that in your original post—thank you for the confirmation.

I cannot reproduce this on my MQTT broker (EMQX), so I assume it has something to do with Mosquitto. Unfortunately, I can't provide direct support on Mosquitto itself. You might consider seeing if any of [Mosquitto's configuration options](https://mosquitto.org/man/mosquitto-conf-5.html) can help; in particular, I would look at:

* `max_keepalive`
* `keepalive_interval`

**Comment by Anto79-ops** [comment]
I don't know if this helps, but I was experiencing something similar when I changed my router...and my new router mashed two devices on the same IP address, and they were having an IP address conflict. The result was what you were experiencing. I rebooted my router and it properly re-assigned the IP address again as they came back alive and the issues was gone.

Not sure if this your problem, but check for IP address conflicts...its  simple fix that it is the problem.

**Comment by pulcov** [comment]
Thank you so much for help. Unfortunately, this is not a IP address conflict because this is 2 kubernetes pod (ecowitt2mqtt and mosquitto) on same cluster.
I will try some configurations and if i don't solve this, i will open an issue in mosquitto project.
