### ISSUE TITLE
Metric conversion results in incorrect values

### ISSUE THREAD

**Issue by oztourer** [bachya/ecowitt2mqtt#43]
**ecowitt2mqtt v1.0.7**

**Describe the bug**
The current code converts the imperial values for rainfall and pressure to integers before converting to metric. This results in a wildly inaccurate pressure value and zero values for rainfall. The conversion should be applied to the original float values. The calculated value for pressure is also out by a factor of 100 (see the diff below).

**To Reproduce**
To confirm this, watch the MQTT output values and compare these with the charts produced by the Ecowitt web site (https://www.ecowitt.net) for the same weather station.

**Expected behavior**
Accurate metric values for rainfall and pressure.

**The fix**
Here is the diff output for the corrected code vs the existing code:

```
98c98
< def in_to_mm(value: int) -> float:
---
> def in_to_mm(value: float) -> float:
103c103
< def inhg_to_hpa(value: int) -> float:
---
> def inhg_to_hpa(value: float) -> float:
105c105
<     return value * 3386.39
---
>     return value * 33.8639
209c209
<                     inhg_to_hpa(int(float(self._data[original_key]))), 1
---
>                     inhg_to_hpa(float(self._data[original_key])), 1
236c236
<                 data[new_key] = round(in_to_mm(int(float(self._data[original_key]))), 1)
---
>                 data[new_key] = round(in_to_mm(float(self._data[original_key])), 1)
```

**Comment by bachya** [comment]
Thanks for the catch, @oztourer!
