### ISSUE TITLE
Feelslike temperature float is oddly specific

### ISSUE THREAD

**Issue by KidA001** [bachya/ecowitt2mqtt#443]
**Describe the bug**
The feels like temperature is returning a float with up to 14 decimal points ex: `38.76319788403144°F`

**To Reproduce**
Observe feelslike. It is not always that high of a decimal place, but due to the math when combining temp, humidity, and wind_speed it often is > 2 places.

**Expected behavior**
Other temperatures only return 2 decimal places so my expectation would be that it would follow that behavior.

**Screenshots**
<img width="219" alt="image" src="https://user-images.githubusercontent.com/8673088/216798957-20931d92-be68-4b8e-aad7-f5b668818d58.png">

**Additional context**
I looked through the code and other temperatures don't seem to have this issue so I would hesitate to modify the `get_temperature_meteocalc_object` function, but that is an option. You could simple add `.quantize(Decimal('1.00'))` in `class FeelsLikeCalculator`

```python
return self.get_calculated_data_point(
  round(feels_like_obj.f, 2), unit_converter=TemperatureConverter
)
```

Open to suggestions and glad to put up a PR

**Comment by bachya** [comment]
See https://github.com/bachya/ecowitt2mqtt/pull/347. You can use the `--precision` flag to round to a certain decimal place (e.g., `--precision=1`). Would that help?

**Comment by KidA001** [comment]
Thank you, that does help and I'll set it on my end. I still do question the default being up to 14-places. Seems like a default of 2 is more than enough but hey sometimes you _really_ gotta know what it feels like :)

**Comment by bachya** [comment]
There are some values—like absolute humidity—that lose identity when rounded at all, so I elected to not round anything unless the user forces it.

At any rate, glad this works for you. I'll close this issue; thanks!
