### ISSUE TITLE
group entities in hass by device

### ISSUE THREAD

**Issue by ErnstEeldert** [bachya/ecowitt2mqtt#48]
Thanks for the awesome work on this, it works like a charm! One enhanced request I would like to make though, is that the discovery setup for hass allows for the sensor entities to be grouped by device. This way, it's much easier to see which sensors are exposed for a given weather station (not just in case of multiple, but even with just one). As a good example, the Shelly integration does this (https://github.com/bieniu/ha-shellies-discovery).

And this is what it looks like in the device registry in hass:

<img width="356" alt="Screenshot 2021-05-19 at 22 59 16" src="https://user-images.githubusercontent.com/8919203/118883758-e39abf80-b8f5-11eb-95d4-79a355a6e96f.png">

Not sure how much work is involved, documentation seems to be somewhat limited on the topic (https://www.home-assistant.io/docs/mqtt/discovery/), but if you're open for it, I might be able to pull together a PR.

Thanks again!

**Comment by bachya** [comment]
I like it! If you have the inclination to try a PR, that would be much appreciated!￼

**Comment by ErnstEeldert** [comment]
Cool! I'll try to scramble something together, might be a week or two before something emerges though :)

**Comment by bachya** [comment]
Great! Thanks, @ErnstEeldert! Will review your PR soon.

**Comment by bachya** [comment]
@ErnstEeldert Are you still planning on working on this? Your PR (#50) was closed due to staleness. Let me know if you plan on re-engaging; otherwise, I'll plan on using your work as a springboard for my own PR. Thanks!
