### ISSUE TITLE
Temperature done in Fahrenheit independent of configuration 

### ISSUE THREAD

**Issue by J2THEG** [bachya/ecowitt2mqtt#497]
Dear all,
I encounter the problem that temperature values are send in Fahrenheit, independent of the configuration. 
I am using the docker image, and set the environment to ECOWITT2MQTT_OUTPUT_UNIT_TEMPERATUR="°C". 

However the MTTQ still recieves values in Fahrenheit. 

Any idea?

**Comment by bachya** [comment]
Your options don't show any alteration to the output unit system:

```json
{
  "mqtt_broker": "mosquitto",
  "mqtt_password": "xxxxx",
  "mqtt_port": "1883",
  "mqtt_topic": "froggit",
  "mqtt_username": "XXXX",
  "verbose": "true"
}
```

In looking at your initial message:

> I encounter the problem that temperature values are send in Fahrenheit, independent of the configuration.
I am using the docker image, and set the environment to ECOWITT2MQTT_OUTPUT_UNIT_TEMPERATUR="°C".

...I notice that you use `ECOWITT2MQTT_OUTPUT_UNIT_TEMPERATUR`—the environment variable is spelled `ECOWITT2MQTT_OUTPUT_UNIT_TEMPERATURE` (notice the `E` at the end). Try fixing that and see if it solves your issue.

**Comment by J2THEG** [comment]
many thanks, looks like this was a layer 8 problem. I had issues updating the docker-compose with the ° character.  Hence this was were i focused on in my analysis.

Again many thanks
