### ISSUE TITLE
Release versioning not semver compliant

### ISSUE THREAD

**Issue by alexdelprete** [bachya/ecowitt2mqtt#533]
Hi Aaron,

I noticed that the app that notifies me about new versions of docker images wasn't notifying me about updates of ecowitt2mqtt. I think the problem is that the versioning used for releases is not semver compliant: `2023.04.0` should be `2023.4.0`.

Not a big deal, but I thought it was better to inform you. :)

**Comment by bachya** [comment]
Hi @alexdelprete!

You mention SemVer, but my libraries use [CalVer](https://calver.org). According to their standard, any of the components can be zero-padded (emphasis mine):

>As seen in the case studies below, projects have found more than one useful way to leverage dates in their versions. Rather than choose a single scheme, CalVer introduces standard terminology for developers, in addition to the "semantic" versions:
>
> * YYYY - Full year - 2006, 2016, 2106
> * YY - Short year - 6, 16, 106
> * **0Y - Zero-padded year - 06, 16, 106**
> * MM - Short month - 1, 2 ... 11, 12
> * **0M - Zero-padded month - 01, 02 ... 11, 12**
> * WW - Short week (since start of year) - 1, 2, 33, 52
> * **0W - Zero-padded week - 01, 02, 33, 52**
> * DD - Short day - 1, 2 ... 30, 31
> * **0D - Zero-padded day - 01, 02 ... 30, 31**

I've published versions under this scheme to PyPI, Docker, and as a HASS add-on for quite some time; I've never run into any issue installing elsewhere.

What app are you using to notify you of new image versions?

**Comment by alexdelprete** [comment]
> What app are you using to notify you of new image versions?

Thanks for the reply and the information about CalVer. Correct me if I'm wrong, you weren't zero-padding in previous releases, correct?

I'm using https://fmartinou.github.io/whats-up-docker

Since I can customize the regexp pattern, I'll try to adapt it to the zero-padded version. :)

**Comment by bachya** [comment]
> Thanks for the reply and the information about CalVer. Correct me if I'm wrong, you weren't zero-padding in all previous releases, correct?

I used to use SemVer, but a _long_ time ago—I've been using this form of CalVer for at least a few years.
 
> For example: `2022.11.3` was not 0-padded. Just wanted to know the criteria so I can adapt.

We only 0-pad the month when doing so produces two digits (because we always want two digits). Using your example above, `2022.011.3` would not have been valid. A good rule to follow: we only 0-pad the month from January through September (1-9).

> I'm using https://fmartinou.github.io/whats-up-docker
> 
> Since I can customize the regexp pattern, I'll try to adapt it to the zero-padded version. :)

Depending on what regex standard your app uses, something like this should work: `\d{4}\.\d{2}\.\d+`

**Comment by alexdelprete** [comment]
Thanks a lot for the info Aaron. :)
