### ISSUE TITLE
If --hass-discovery and --mqtt-topic are provided, send both types of message

### ISSUE THREAD

**Issue by russss** [bachya/ecowitt2mqtt#543]
I want to use both mqtt2prometheus and Home Assistant to listen to these messages. The "normal" style messages are much easier to handle with mqtt2prometheus than the Home Assistant style.

It would be nice if ecowitt2mqtt could send both types of message if I request it to. At the moment it seems that the `--hass-discovery` flag disables the normal-style messages.

**Comment by bachya** [comment]
How would you propose configuring this scenario? It seems strange that including both options would mean "publish to the same broker in two different formats."

**Comment by russss** [comment]
Well, at the moment if the `--hass-discovery` option is supplied then it takes precedence, which is not very clear from the documentation.

The Home Assistant-style messages are verbose and annoying to consume with most other MQTT consumers. The standard method, with all the data in a single message, is a lot easier. I just remembered I have another consumer which sends off a packet of weather data to a service elsewhere - if I had to adapt that to use the Home Assistant style of messages, it would significantly increase the complexity because I'd have to wait to receive all the messages before sending it off.

I don't really see the problem with sending both types of message if `--hass-discovery` is enabled - it's hardly any additional data compared to the Home Assistant messages. I can always fork and add this myself but I suspect I'm not going to be the only person with this issue.

**Comment by bachya** [comment]
> I don't really see the problem with sending both types of message if --hass-discovery is enabled - it's hardly any additional data compared to the Home Assistant messages.

The challenge isn't related to resources—it's related to the configuration "interface". I don't think most users would find it clear that providing both flags means that both formats are published (especially if we have other formats over time).

That said, your overall request is certainly reasonable. I think on the right way to do it—I'm thinking that expanding the [configuration file](https://github.com/bachya/ecowitt2mqtt#configuration-file) to allow for multiple configurations for the same gateway might be optimal.

**Comment by EnsuingRequiem** [comment]
> > I don't really see the problem with sending both types of message if --hass-discovery is enabled - it's hardly any additional data compared to the Home Assistant messages.
> 
> The challenge isn't related to resources—it's related to the configuration "interface". I don't think most users would find it clear that providing both flags means that both formats are published (especially if we have other formats over time).
> 
> That said, your overall request is certainly reasonable. I think on the right way to do it—I'm thinking that expanding the [configuration file](https://github.com/bachya/ecowitt2mqtt#configuration-file) to allow for multiple configurations for the same gateway might be optimal.

I fully expect the data to published both ways. Using other mqtt integrations as examples, valetudo publishes both to the homeassistant topic as well as whatever I've defined and the same applies for rtlamr2mqtt. I'm only just setting up Home Assistant, but I'd like to be able to fall back to any other setup I currently have for consuming the mqtt data such as Node-RED or a tsdb

**Comment by bachya** [comment]
FYI, this was released in [2023.06.0](https://github.com/bachya/ecowitt2mqtt/releases/tag/2023.06.0).
