### ISSUE TITLE
Cannot install ecowitt2mqtt

### ISSUE THREAD

**Issue by AnthonyBorton** [bachya/ecowitt2mqtt#61]
Hi,

I'm creating this as an issue rather then a bug as I'm sure it's probably something I'm doing wrong :)

I wanted to install ecowitt2mqtt on a newly installed RaspberryPi 3 I had lying around. I'm much more familiar with Windows than I am with any flavour of Linux so please be kind.

I have updated the installation to ensure I have the latest version of all the packages installed.

When I try to install ecowitt2mqtt, I get the following error.  Can anyone point me in the right direction?

```pi@utilitypi:~ $ pip install ecowitt2mqtt
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting ecowitt2mqtt
  Could not find a version that satisfies the requirement ecowitt2mqtt (from versions: )
No matching distribution found for ecowitt2mqtt
```

Thanks
Anthony

**Comment by bachya** [comment]
How are you attempting to install?

**Comment by AnthonyBorton** [comment]
Sorry - I didn't realise that wasn't in the snippet I copy/pasted 🙄 

On the freshly installed and updated Raspberry OS install, I open a terminal window and use the following command that I've copy/pasted from your readme.

```pip install ecowitt2mqtt```

The snippet I included initially is what is returned.

**Comment by AnthonyBorton** [comment]
OK. I read something unrelated overnight my time and tried..

```pip3 install ecowitt2mqtt```

This appears to have worked.

**Comment by bachya** [comment]
Great! Will close this out.
