### ISSUE TITLE
Install error on windows x64

### ISSUE THREAD

**Issue by d-jewell** [bachya/ecowitt2mqtt#644]
**Describe the bug**
when running the PIP install for ecowitt2mqtt the install fails to complete.  An error is given saying   
Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output] 
I also noticed the following error RuntimeError: uvloop does not support Windows at the moment

**To Reproduce**
Windows 10 x86, PY 3.11 
pip install ecowitt2mqtt

**Expected behavior**
Install would complete without errors

**Screenshots**
![image](https://github.com/bachya/ecowitt2mqtt/assets/20908837/9231cbf5-411d-4809-8e73-36f7f8b02b8d)
![image](https://github.com/bachya/ecowitt2mqtt/assets/20908837/e1a8118b-d06a-407a-84a7-21eb689e47dd)

**Additional context**

**Comment by bachya** [comment]
The log tells you what is going on:

```
RuntimeError: uvloop does not support Windows at the moment
```

`uvloop` is a dependency of this library—if it doesn't support Windows installations via `pip`, we can't, either. You might consider installing via [the Docker image](https://github.com/bachya/ecowitt2mqtt#docker).
