### ISSUE TITLE
Unknown device model ("WS2900_V2.01.14")

### ISSUE THREAD

**Issue by reba0** [bachya/ecowitt2mqtt#67]
**ecowitt2mqtt version**
image: bachya/ecowitt2mqtt:latest

**Describe the bug**
Unknown device model ("WS2900_V2.01.14")

**To Reproduce**
Remark: (UNIT_SYSTEM=metric)
Today at 07:12:17 INFO:ecowitt2mqtt:Unknown device model ("WS2900_V2.01.14"); 
please report it at https://github.com/bachya/ecowitt2mqtt
today at 07:12:17 INFO:ecowitt2mqtt:Published to sensors/efws2900: 
{'tempin': 19.6, 'humidityin': 65.0, 'baromrel': 1011.2437818, 'baromabs': 941.3148283, 'temp': 12.2, 'humidity': 99.0, 'winddir': 196.33948, 'windspeed': 0.0, 'windgust': 0.0, 'maxdailygust': 2.2, 'rainrate': 0.0, 'eventrain': 11.7094, 'hourlyrain': 0.0, 'dailyrain': 0.508, 'weeklyrain': 33.502599999999994, 'monthlyrain': 33.502599999999994, 'totalrain': 64.4906, 'solarradiation': 13.33, 'uv': 0.0, 'wh65batt': 'off', 'dewpoint': 12.1, 'feelslike': 12.2, 'heatindex': 12.1, 'solarradiation_lux': 1687.3, 'solarradiation_perceived': 65.0, 'windchill': None}

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/77356925/128127513-1a3eacb0-40a7-4bd1-b5d1-d32453dfe02a.png)

**Additional context**
Hi  Many thanks for the nice application
I got the information that I should report it in the log to unknown Model  (  Model is  efws2900 ) 
In the log I saw that some Values are very  long might be  a chance to correct them  to  2 decimals 
windchill should be be a value  otherwise it is not possible to make a graph  in grafana 
If you need more information please let me know 

Many thanks for your help 
Best regards 
Reto

**Comment by bachya** [comment]
Thanks for your report! Can you please set hour log level to `DEBUG` and show me the data as it's received from your unit (before this particular error)?

**Comment by reba0** [comment]
Hi Aron 

Many thanks for  your response 

Please find log in debug modus attached 

 

Seems there are some fields also missing 

 

Let me know if I can help further 

 

Best regards 

Reto 

 

Thanks for your report! Can you please set hour log level to DEBUG

 

 and show me the data as it's received from your unit (before this particular error)?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by bachya** [comment]
@reba0 I don't see the logs you mention.

**Comment by reba0** [comment]
Hi  Aron  
Sorry replied on email with attchment.  Seems  no to work   attached here directly 
[e8b6e19b281b.log](https://github.com/bachya/ecowitt2mqtt/files/6937696/e8b6e19b281b.log)

Best regards 
Reto
