### ISSUE TITLE
Decimals in Metric very long 

### ISSUE THREAD

**Issue by reba0** [bachya/ecowitt2mqtt#70]
**ecowitt2mqtt version**
latstes 

**Describe the solution you'd like**
Decimals in Metric ar verry long might be goot to shertem them 

![image](https://user-images.githubusercontent.com/77356925/128335097-b72a7a4d-573a-497c-90f9-76436bb746d8.png)

Debug Log file and Excel attached 

best regards
[e8b6e19b281b.log](https://github.com/bachya/ecowitt2mqtt/files/6937885/e8b6e19b281b.log)
[Weather Station Values .xlsx](https://github.com/bachya/ecowitt2mqtt/files/6937886/Weather.Station.Values.xlsx)
Reto

**Comment by bachya** [comment]
Fixed via #69.

**Comment by bachya** [comment]
Actually, more work is needed here.
