### ISSUE TITLE
Docker Problem

### ISSUE THREAD

**Issue by ljpaff** [bachya/ecowitt2mqtt#705]
i'm triying to run docker imagen on a Rpi 4 with Raspbian GNU/Linux 10 (buster):
When i'm using docker command:
>docker run -it \\
   -e MQTT_BROKER=myserver.com \\
    -e MQTT_USERNAME=xxxxxxx \\
    -e MQTT_PASSWORD=yyyyyyy \\
    -p 8080:8080 \\
    bachya/ecowitt2mqtt:latest

I'm getting this error:

>Digest: sha256:69c9bc16539bcdb4b4058c5de5327a7070ea16257aab878ecef40254bded0f13
Status: Downloaded newer image for bachya/ecowitt2mqtt:latest
Traceback (most recent call last):
  File "/venv/bin/ecowitt2mqtt", line 5, in <module>
    from ecowitt2mqtt.__main__ import main
  File "/venv/lib/python3.9/site-packages/ecowitt2mqtt/__main__.py", line 10, in <module>
    import uvloop
  File "/venv/lib/python3.9/site-packages/uvloop/__init__.py", line 7, in <module>
    from .loop import Loop as __BaseLoop  # NOQA
ImportError: Error loading shared library ld-linux-armhf.so.3: No such file or directory (needed by /venv/lib/python3.9/site-packages/uvloop/loop.cpython-39-arm-linux-gnueabihf.so)

What is going wrong?

I have tried latest and dev branch

**Comment by bachya** [comment]
Are you using a 32-bit or 64-bit version of Raspbian?
