### ISSUE TITLE
baromrel and baromabs values are incorrect

### ISSUE THREAD

**Issue by zechnkaas** [bachya/ecowitt2mqtt#76]
**ecowitt2mqtt version**
docker 1.3.0

**Describe the bug**
barometric pressure values are somehow bugged, and round to specific values.

948,2
951,6
955

**To Reproduce**
i upgraded from 1.0.11 to 1.3.0

**Expected behavior**
correct values like in V 1.0.11

**Screenshots**
![ecowitt2mqtt](https://user-images.githubusercontent.com/7140356/129643861-d002995e-b420-4e4d-8de2-f87462f1d60e.JPG)

**Additional context**
after downgrade to 1.0.11 the values are correct again

**Comment by bachya** [comment]
Please provide more detail; I'm not sure how to address "bugged" values. Thanks!

**Comment by zechnkaas** [comment]
could you tell me what you would like to have in detail? your logs do match the values that homeassistant is receiving, so i am sure it is something on ecowitt23mqtt side.

so far today the chart look like this:

![ecowitt2mqtt2](https://user-images.githubusercontent.com/7140356/129712592-0d5be949-0ba4-4a91-97e4-22106cf5dd6c.JPG)

the values are:
948.2
951.6
955
958.3

always fixed

here the chart as compare from ecowitt.net

![image](https://user-images.githubusercontent.com/7140356/129713037-5da345d8-fbd4-41b6-b413-746737a927d0.png)


here is a catured http post from the station and the debug log:

`POST /data/report HTTP/1.1
HOST: 192.168.10.10
Connection: Close
Content-Type: application/x-www-form-urlencoded
Content-Length: 447

PASSKEY=E1C8F5DB61727A4F96860CE96C64480F&stationtype=EasyWeatherV1.5.9&dateutc=2021-08-17+10:27:26&tempinf=74.8&humidityin=57&baromrelin=29.959&baromabsin=28.252&tempf=60.8&humidity=63&winddir=289&windspeedmph=5.4&windgustmph=6.9&maxdailygust=18.3&rainratein=0.000&eventrainin=1.421&hourlyrainin=0.000&dailyrainin=0.091&weeklyrainin=1.421&monthlyrainin=5.020&totalrainin=14.980&solarradiation=216.90&uv=2&wh65batt=0&freq=868M&model=WS2900_V2.01.13`

DEBUG:ecowitt2mqtt:Received data from Ecowitt device: {'PASSKEY': 'E1C8F5DB61727A4F96860CE96C64480F', 'stationtype': 'EasyWeatherV1.5.9', 'dateutc': '2021-08-17 10:27:26', 'tempinf': '74.8', 'humidityin': '57', 'baromrelin': '29.959', 'baromabsin': '28.252', 'tempf': '60.8', 'humidity': '63', 'winddir': '289', 'windspeedmph': '5.4', 'windgustmph': '6.9', 'maxdailygust': '18.3', 'rainratein': '0.000', 'eventrainin': '1.421', 'hourlyrainin': '0.000', 'dailyrainin': '0.091', 'weeklyrainin': '1.421', 'monthlyrainin': '5.020', 'totalrainin': '14.980', 'solarradiation': '216.90', 'uv': '2', 'wh65batt': '0', 'freq': '868M', 'model': 'WS2900_V2.01.13'},
INFO:ecowitt2mqtt:Unknown device; please report it at https://github.com/bachya/ecowitt2mqtt (payload: {'PASSKEY': 'E1C8F5DB61727A4F96860CE96C64480F', 'stationtype': 'EasyWeatherV1.5.9', 'dateutc': '2021-08-17 10:27:26', 'tempinf': '74.8', 'humidityin': '57', 'baromrelin': '29.959', 'baromabsin': '28.252', 'tempf': '60.8', 'humidity': '63', 'winddir': '289', 'windspeedmph': '5.4', 'windgustmph': '6.9', 'maxdailygust': '18.3', 'rainratein': '0.000', 'eventrainin': '1.421', 'hourlyrainin': '0.000', 'dailyrainin': '0.091', 'weeklyrainin': '1.421', 'monthlyrainin': '5.020', 'totalrainin': '14.980', 'solarradiation': '216.90', 'uv': '2', 'wh65batt': '0', 'freq': '868M', 'model': 'WS2900_V2.01.13'}),
DEBUG:ecowitt2mqtt:Wind Chill Temperature is only defined for temperatures at or below 50 F and wind speeds above 3 mph. (temperature: 60.8, wind speed: 5.4),
DEBUG:ecowitt2mqtt:Publishing according to Home Assistant MQTT Discovery standard,
DEBUG:ecowitt2mqtt:Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b'',
DEBUG:ecowitt2mqtt:Received CONNACK (0, 0),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m1), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/tempin/config'', ... (513 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m2), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/tempin/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m3), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/tempin/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m4), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/humidityin/config'', ... (520 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m5), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/humidityin/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m6), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/humidityin/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m7), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/baromrel/config'', ... (514 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m8), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/baromrel/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m9), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/baromrel/state'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m10), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/baromabs/config'', ... (514 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m11), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/baromabs/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m12), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/baromabs/state'', ... (5 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m13), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/temp/config'', ... (505 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m14), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/temp/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m15), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/temp/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m16), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/humidity/config'', ... (512 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m17), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/humidity/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m18), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/humidity/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m19), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/winddir/config'', ... (514 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m20), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/winddir/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m21), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/winddir/state'', ... (5 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m22), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/windspeed/config'', ... (520 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m23), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/windspeed/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m24), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/windspeed/state'', ... (3 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m25), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/windgust/config'', ... (516 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m26), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/windgust/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m27), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/windgust/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m28), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/maxdailygust/config'', ... (532 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m29), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/maxdailygust/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m30), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/maxdailygust/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m31), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/rainrate/config'', ... (506 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m32), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/rainrate/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m33), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/rainrate/state'', ... (3 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m34), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/eventrain/config'', ... (510 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m35), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/eventrain/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m36), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/eventrain/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m37), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/hourlyrain/config'', ... (514 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m38), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/hourlyrain/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m39), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/hourlyrain/state'', ... (3 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m40), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/dailyrain/config'', ... (510 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m41), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/dailyrain/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m42), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/dailyrain/state'', ... (3 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m43), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/weeklyrain/config'', ... (514 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m44), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/weeklyrain/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m45), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/weeklyrain/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m46), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/monthlyrain/config'', ... (518 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m47), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/monthlyrain/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m48), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/monthlyrain/state'', ... (5 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m49), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/totalrain/config'', ... (510 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m50), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/totalrain/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m51), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/totalrain/state'', ... (5 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m52), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/solarradiation/config'', ... (543 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m53), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/solarradiation/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m54), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/solarradiation/state'', ... (5 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m55), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/uv/config'', ... (496 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m56), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/uv/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m57), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/uv/state'', ... (3 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m58), 'b'homeassistant/binary_sensor/E1C8F5DB61727A4F96860CE96C64480F/wh65batt/config'', ... (497 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m59), 'b'homeassistant/binary_sensor/E1C8F5DB61727A4F96860CE96C64480F/wh65batt/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m60), 'b'homeassistant/binary_sensor/E1C8F5DB61727A4F96860CE96C64480F/wh65batt/state'', ... (3 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m61), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/dewpoint/config'', ... (517 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m62), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/dewpoint/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m63), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/dewpoint/state'', ... (3 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m64), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/feelslike/config'', ... (521 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m65), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/feelslike/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m66), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/feelslike/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m67), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/heatindex/config'', ... (521 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m68), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/heatindex/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m69), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/heatindex/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m70), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/solarradiation_lux/config'', ... (556 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m71), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/solarradiation_lux/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m72), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/solarradiation_lux/state'', ... (7 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m73), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/solarradiation_perceived/config'', ... (579 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m74), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/solarradiation_perceived/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m75), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/solarradiation_perceived/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m76), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/windchill/config'', ... (523 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r0, m77), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/windchill/availability'', ... (6 bytes),
DEBUG:ecowitt2mqtt:Sending PUBLISH (d0, q0, r1, m78), 'b'homeassistant/sensor/E1C8F5DB61727A4F96860CE96C64480F/windchill/state'', ... (4 bytes),
DEBUG:ecowitt2mqtt:Sending DISCONNECT,
INFO:ecowitt2mqtt:Published to HASS discovery: {'tempin': 23.8, 'humidityin': 57.0, 'baromrel': 1015.9, 'baromabs': 958.3, 'temp': 16.0, 'humidity': 63.0, 'winddir': 465.1, 'windspeed': 8.7, 'windgust': 11.1, 'maxdailygust': 18.3, 'rainrate': 0.0, 'eventrain': 35.6, 'hourlyrain': 0.0, 'dailyrain': 2.5, 'weeklyrain': 35.6, 'monthlyrain': 127.0, 'totalrain': 381.0, 'solarradiation': 216.9, 'uv': 2.0, 'wh65batt': 'off', 'dewpoint': 9.0, 'feelslike': 16.0, 'heatindex': 15.3, 'solarradiation_lux': 27455.7, 'solarradiation_perceived': 89.0, 'windchill': None},

hope that helps?

**Comment by bachya** [comment]
Sorry, I'm still not following what the problem is. Looking at the payload you posted above, your device sends these values for pressure:

```
"baromrelin": "29.959"
"baromabsin": "28.252"
```

The values that are sent to HASS:

```
"baromrel": 1015.9
"baromabs": 958.3
```

I assume you're using metric units, yes? In that case, the math checks out (account for the fact that values are rounded when first imported, then rounded again after conversion from imperial to metric):

```
29.959 * 33.8639 = 1014.5285801
28.252 * 33.8639 = 956.7229028
```

**Comment by zechnkaas** [comment]
Hello,
yes I use metric.

I switched back yesterday to 1.0.11 in docker and it does look good again? I will try to capture more http requests and i switch to 1.3.0 again.

![image](https://user-images.githubusercontent.com/7140356/130152500-cfe8134d-55f4-49b8-b94d-005927c42c06.png)

**Comment by bachya** [comment]
I think part of the problem might be the newer versions round the decimal point something smaller. Since you're combining the old version – which had a lot of intermediate decimal points – in this newer version, your graph is going to look like that. I'd be curious to see what would happen if you let it run for a day or so on the newest version￼.￼

**Comment by zechnkaas** [comment]
24h chart does now look like this

![image](https://user-images.githubusercontent.com/7140356/130314996-c4edf33e-67c3-44dc-a82c-1e40cdf54926.png)

**Comment by bachya** [comment]
Thanks for that, @zechnkaas. It looks like pressure will fluctuate in fairly small increments – since I'm rounding to one decimal point, that effectively chops off several intermediate values. I'll back off on the rounding for this one.

**Comment by zechnkaas** [comment]
Hi,
yea was about just writing that most webservices are using at least one decimal point. Wunderground is even using 2 decimal. but I think one would be enough.

thanks.
