### ISSUE TITLE
Wind direction values are not correct. In some cases >360 degrees. 

### ISSUE THREAD

**Issue by kjjordans** [bachya/ecowitt2mqtt#91]
**ecowitt2mqtt version**
the current docker image on docker hub

**Describe the bug**
the winddir values reported do not match the values on the LCD
in some cases, they are >360 degrees.

**To Reproduce**
ecowitt on docker with the following settings

|ENV KEY| VALUE|
|---|---|
|GPG_KEY | E3FF2839C048B25C084DEBE9B26995E310250568|
|HASS_DISCOVERY | true|
||INPUT_UNIT_SYSTEM | imperial|
|LANG | C.UTF-8|
|MQTT_BROKER | 192.168.20.19|
|MQTT_PASSWORD | ????|
|MQTT_TOPIC | Local_Weather|
|MQTT_USERNAME | ????|
|OUTPUT_UNIT_SYSTEM | metric|
|PATH | /usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin|
|PYTHON_GET_PIP_SHA256 | 8890955d56a8262348470a76dc432825f61a84a54e2985a86cd520f656a6e220|
|PYTHON_GET_PIP_URL | https://github.com/pypa/get-pip/raw/936e08ce004d0b2fae8952c50f7ccce1bc578ce5/public/get-pip.py|
|PYTHON_PIP_VERSION | 21.1.2|
|PYTHON_VERSION | 3.9.5|

**Weather station**'

WS-2902C
by Ambient Weather
Firmware: EasyWeatherV1.5.9 

**Expected behavior**
direction values on the LCD display should match those in the MQTT

**Additional context**
```INFO:ecowitt2mqtt:Published to HASS discovery: {'tempin': 21.3, 'humidityin': 51, 'baromrel': 998.138, 'baromabs': 970.743, 'temp': 12.2, 'humidity': 80, 'winddir': 415.2, 'windspeed': 4.7, 'windgust': 5.5, 'maxdailygust': 19.5, 'rainrate': 0.0, 'eventrain': 0.0, 'hourlyrain': 0.0, 'dailyrain': 0.0, 'weeklyrain': 0.0, 'monthlyrain': 22.4, 'totalrain': 22.4, 'solarradiation': 0.0, 'uv': 0, 'wh65batt': 'off', 'dewpoint': 8.9, 'feelslike': 12.2, 'heatindex': 11.6, 'solarradiation_lux': 0.0, 'solarradiation_perceived': 0.0, 'windchill': None}
```

**Comment by bachya** [comment]
Please set your ecowitt2mqtt logs to `DEBUG` and paste what output you get after 30 seconds or so.
